// Question bank for IGIT Connect mock-test platform.
// 3 categories x 3 difficulties x 25 questions = 225 total.
// Each entry: { question, options: [4 strings], answer: index 0..3, category, difficulty }

// ----------------------------- APTITUDE -----------------------------
const aptitudeEasy = [
  { question: "What is 25% of 200?", options: ["25", "40", "50", "75"], answer: 2 },
  { question: "The average of 4, 8 and 12 is", options: ["6", "7", "8", "10"], answer: 2 },
  { question: "If a pen costs Rs. 12, what do 7 pens cost?", options: ["Rs. 72", "Rs. 84", "Rs. 96", "Rs. 100"], answer: 1 },
  { question: "Simple interest on Rs. 1000 at 10% per annum for 2 years is", options: ["Rs. 100", "Rs. 200", "Rs. 250", "Rs. 300"], answer: 1 },
  { question: "Which is the smallest fraction: 2/3, 3/5, 4/7, 5/9?", options: ["2/3", "3/5", "4/7", "5/9"], answer: 3 },
  { question: "If x + 5 = 12, what is x?", options: ["5", "6", "7", "8"], answer: 2 },
  { question: "The ratio of 2 hours to 30 minutes is", options: ["2:1", "4:1", "6:1", "8:1"], answer: 1 },
  { question: "How many seconds are there in 3 hours?", options: ["7200", "10800", "12000", "18000"], answer: 1 },
  { question: "If 4x = 36, then x =", options: ["6", "7", "8", "9"], answer: 3 },
  { question: "Square root of 144 is", options: ["10", "11", "12", "14"], answer: 2 },
  { question: "20% of 50 is equal to", options: ["8", "10", "12", "15"], answer: 1 },
  { question: "A train travels 60 km in 1 hour. Its speed in m/s is approximately", options: ["15", "16.67", "20", "25"], answer: 1 },
  { question: "Sum of angles in a triangle is", options: ["90 deg", "120 deg", "180 deg", "360 deg"], answer: 2 },
  { question: "Which number is prime?", options: ["9", "15", "21", "23"], answer: 3 },
  { question: "The next number in 2, 4, 8, 16, ___ is", options: ["20", "24", "32", "64"], answer: 2 },
  { question: "If 5 pencils cost Rs. 25, the cost of 8 pencils is", options: ["Rs. 35", "Rs. 40", "Rs. 45", "Rs. 50"], answer: 1 },
  { question: "Cube of 4 is", options: ["12", "16", "32", "64"], answer: 3 },
  { question: "LCM of 4 and 6 is", options: ["6", "10", "12", "24"], answer: 2 },
  { question: "HCF of 12 and 18 is", options: ["3", "4", "6", "9"], answer: 2 },
  { question: "If A:B = 2:3 and B:C = 4:5, then A:C =", options: ["6:5", "8:15", "8:5", "2:5"], answer: 1 },
  { question: "30% of x = 60. What is x?", options: ["100", "150", "180", "200"], answer: 3 },
  { question: "What comes next: 1, 4, 9, 16, ___?", options: ["20", "23", "25", "27"], answer: 2 },
  { question: "Half of 1/4 is", options: ["1/2", "1/3", "1/6", "1/8"], answer: 3 },
  { question: "Perimeter of a square with side 5 cm is", options: ["10 cm", "15 cm", "20 cm", "25 cm"], answer: 2 },
  { question: "If today is Monday, the day after 100 days will be", options: ["Tuesday", "Wednesday", "Thursday", "Friday"], answer: 1 },
];

const aptitudeModerate = [
  { question: "A man buys an article for Rs. 200 and sells it for Rs. 250. His profit % is", options: ["20%", "25%", "30%", "40%"], answer: 1 },
  { question: "Two trains, 100m and 80m long, travel in opposite directions at 36 and 54 km/h. Time to cross each other is", options: ["6.4 s", "7.2 s", "8.0 s", "9.0 s"], answer: 1 },
  { question: "Compound interest on Rs. 5000 at 10% p.a. for 2 years is", options: ["Rs. 1000", "Rs. 1050", "Rs. 1100", "Rs. 1150"], answer: 1 },
  { question: "The average age of 5 boys is 12 years. If a 6th boy aged 18 joins, new average is", options: ["12", "13", "14", "15"], answer: 1 },
  { question: "If 8 men finish a job in 12 days, 12 men will finish it in", options: ["6 days", "8 days", "10 days", "16 days"], answer: 1 },
  { question: "A boat goes 30 km upstream in 5 h and 30 km downstream in 3 h. Stream speed is", options: ["1 km/h", "2 km/h", "3 km/h", "4 km/h"], answer: 1 },
  { question: "Selling at Rs. 480, a shopkeeper loses 20%. Cost price is", options: ["Rs. 540", "Rs. 580", "Rs. 600", "Rs. 640"], answer: 2 },
  { question: "If x^2 - 5x + 6 = 0, the roots are", options: ["1, 6", "2, 3", "-2, -3", "1, 5"], answer: 1 },
  { question: "Mean of 10 numbers is 20. If 25 and 35 are removed, new mean is", options: ["17.5", "18", "18.75", "20"], answer: 0 },
  { question: "Pipe A fills a tank in 10 min, B in 15 min. Together they fill it in", options: ["5 min", "6 min", "7 min", "8 min"], answer: 1 },
  { question: "A sum doubles in 8 years at simple interest. Rate is", options: ["10%", "12%", "12.5%", "15%"], answer: 2 },
  { question: "Which is greater: 2^3, 3^2, 5^1?", options: ["2^3", "3^2", "5^1", "All equal"], answer: 1 },
  { question: "If sin theta = 1/2, theta in degrees is", options: ["30", "45", "60", "90"], answer: 0 },
  { question: "A clock loses 5 minutes every hour. After 12 hours, it shows time behind by", options: ["30 min", "45 min", "60 min", "75 min"], answer: 2 },
  { question: "P and Q started a business with Rs. 5000 and Rs. 7500. Profit ratio is", options: ["1:2", "2:3", "5:7", "5:8"], answer: 1 },
  { question: "Discount of 15% on a Rs. 800 article gives selling price", options: ["Rs. 600", "Rs. 660", "Rs. 680", "Rs. 720"], answer: 2 },
  { question: "Average of first 5 multiples of 7 is", options: ["14", "17.5", "21", "28"], answer: 2 },
  { question: "A number, when doubled and reduced by 8, equals 30. The number is", options: ["17", "18", "19", "21"], answer: 2 },
  { question: "If 60% of A = 75% of B, then A:B is", options: ["3:4", "4:5", "5:4", "9:10"], answer: 2 },
  { question: "Probability of getting at least one head in 2 coin tosses is", options: ["1/4", "1/2", "3/4", "1"], answer: 2 },
  { question: "A man covers 3 km in 30 minutes. His speed in km/h is", options: ["3", "4", "5", "6"], answer: 3 },
  { question: "Successive discounts of 10% and 20% are equivalent to a single discount of", options: ["25%", "27%", "28%", "30%"], answer: 2 },
  { question: "If radius of a circle is doubled, area becomes", options: ["2x", "3x", "4x", "8x"], answer: 2 },
  { question: "Sum of first 20 natural numbers is", options: ["190", "200", "210", "220"], answer: 2 },
  { question: "If a:b = 3:4 and b:c = 8:9, then a:b:c =", options: ["3:4:9", "6:8:9", "12:16:18", "9:12:16"], answer: 1 },
];

const aptitudeHard = [
  { question: "From a pack of 52 cards, probability of drawing a king or a heart is", options: ["1/13", "4/13", "16/52", "17/52"], answer: 1 },
  { question: "How many ways can the letters of MISSISSIPPI be arranged?", options: ["34650", "39916800", "40320", "11!/4!"], answer: 0 },
  { question: "A number is divisible by 6 and 8 but not 5. Smallest such positive integer is", options: ["24", "48", "72", "120"], answer: 0 },
  { question: "If log10 2 = 0.301, then log10 5 ≈", options: ["0.602", "0.699", "0.778", "0.845"], answer: 1 },
  { question: "Three pipes A, B, C fill a tank in 6, 8, 12 hours. Together they fill in", options: ["8/3 h", "24/9 h", "8/9 h", "2 h"], answer: 0 },
  { question: "Sum of an infinite GP with a=4, r=1/2 is", options: ["6", "7", "8", "10"], answer: 2 },
  { question: "Number of ways to seat 5 people around a round table is", options: ["120", "60", "24", "240"], answer: 2 },
  { question: "60% acid mixed with 30% acid forms 4 L of 50% solution. Volume of 60% solution is", options: ["1.5 L", "2 L", "2.67 L", "3 L"], answer: 2 },
  { question: "If P(A)=0.4, P(B)=0.5 and A,B independent, P(A∩B) =", options: ["0.1", "0.2", "0.4", "0.9"], answer: 1 },
  { question: "Number of trailing zeros in 100! is", options: ["20", "22", "24", "25"], answer: 2 },
  { question: "If x = 3+2*sqrt(2), then x + 1/x =", options: ["4", "5", "6", "8"], answer: 2 },
  { question: "Sides of a triangle are 7, 8, 9. Its area (Heron's formula) ≈", options: ["24.0", "26.83", "28.0", "30.0"], answer: 1 },
  { question: "If a, b, c are in HP and a=2, c=6, then b =", options: ["3", "3.5", "4", "5"], answer: 0 },
  { question: "20 men complete a job in 24 days at 8 h/day. To finish in 20 days at 6 h/day, men needed =", options: ["28", "30", "32", "36"], answer: 2 },
  { question: "Roots of x^2 + 4x + 5 = 0 are", options: ["real distinct", "real equal", "complex conjugates", "rational"], answer: 2 },
  { question: "Number of diagonals in a regular polygon with 10 sides is", options: ["20", "25", "35", "45"], answer: 2 },
  { question: "From 6 boys and 4 girls, a committee of 5 with at least 2 girls. Number of ways =", options: ["120", "186", "246", "300"], answer: 2 },
  { question: "Limit as x→0 of (sin 3x)/x equals", options: ["0", "1", "3", "infinite"], answer: 2 },
  { question: "Volume of a sphere of radius 6 cm is (in cm^3)", options: ["288 pi", "216 pi", "144 pi", "904 pi"], answer: 0 },
  { question: "If 2^x = 32 and 3^y = 81, then x + y =", options: ["7", "8", "9", "10"], answer: 2 },
  { question: "How many integers between 1 and 1000 are divisible by 7 but not by 3?", options: ["95", "96", "100", "143"], answer: 1 },
  { question: "Area enclosed by y = x^2, y = 4 is", options: ["16/3", "32/3", "8", "16"], answer: 1 },
  { question: "Standard deviation of 2, 4, 4, 4, 5, 5, 7, 9 is", options: ["1.5", "2", "2.45", "3"], answer: 1 },
  { question: "Number of solutions of |x-2| + |x+3| = 5 in real numbers is", options: ["1", "2", "infinite", "0"], answer: 2 },
  { question: "If A = ((1,2),(3,4)), determinant of A is", options: ["-2", "0", "2", "10"], answer: 0 },
];

// ----------------------------- ENGLISH -----------------------------
const englishEasy = [
  { question: "Synonym of HAPPY", options: ["sad", "joyful", "angry", "tired"], answer: 1 },
  { question: "Antonym of BEGIN", options: ["start", "open", "end", "go"], answer: 2 },
  { question: "Choose correctly spelled word", options: ["recieve", "receive", "receeve", "recive"], answer: 1 },
  { question: "Plural of CHILD", options: ["childs", "childes", "children", "childrens"], answer: 2 },
  { question: "Past tense of GO", options: ["goed", "went", "gone", "going"], answer: 1 },
  { question: "Article needed: ___ apple a day keeps the doctor away.", options: ["A", "An", "The", "No article"], answer: 1 },
  { question: "Synonym of BIG", options: ["tiny", "huge", "narrow", "weak"], answer: 1 },
  { question: "Antonym of FAST", options: ["quick", "rapid", "slow", "swift"], answer: 2 },
  { question: "Choose the correct sentence", options: ["He don't like tea.", "He doesn't likes tea.", "He doesn't like tea.", "He didn't likes tea."], answer: 2 },
  { question: "Synonym of START", options: ["finish", "begin", "stop", "halt"], answer: 1 },
  { question: "Antonym of HOT", options: ["warm", "cool", "cold", "boiling"], answer: 2 },
  { question: "Past tense of EAT", options: ["eated", "ate", "eaten", "eating"], answer: 1 },
  { question: "Plural of MOUSE (animal)", options: ["mouses", "mice", "mouse", "meeces"], answer: 1 },
  { question: "Choose the noun: She runs fast.", options: ["She", "runs", "fast", "none"], answer: 0 },
  { question: "Choose the verb: The dog barks loudly.", options: ["The", "dog", "barks", "loudly"], answer: 2 },
  { question: "Antonym of OPEN", options: ["unlock", "shut", "wide", "loose"], answer: 1 },
  { question: "Synonym of SMART", options: ["dumb", "clever", "rude", "rough"], answer: 1 },
  { question: "Article: He is ___ honest man.", options: ["a", "an", "the", "no article"], answer: 1 },
  { question: "Past tense of WRITE", options: ["writed", "wrote", "written", "writing"], answer: 1 },
  { question: "Antonym of TRUE", options: ["honest", "real", "false", "right"], answer: 2 },
  { question: "Synonym of QUICK", options: ["fast", "slow", "lazy", "long"], answer: 0 },
  { question: "Plural of LEAF", options: ["leafs", "leaves", "leafes", "leavs"], answer: 1 },
  { question: "Choose the adjective: The red car is fast.", options: ["The", "red", "car", "is"], answer: 1 },
  { question: "Past tense of BUY", options: ["buyed", "bought", "buyt", "buying"], answer: 1 },
  { question: "Antonym of EASY", options: ["simple", "soft", "hard", "smooth"], answer: 2 },
];

const englishModerate = [
  { question: "Idiom: 'Bury the hatchet' means", options: ["Hide a weapon", "Make peace", "Start a fight", "Lose interest"], answer: 1 },
  { question: "Synonym of DILIGENT", options: ["lazy", "hardworking", "careless", "rude"], answer: 1 },
  { question: "Antonym of CONCEAL", options: ["hide", "reveal", "cover", "mask"], answer: 1 },
  { question: "Idiom: 'A blessing in disguise' means", options: ["A hidden curse", "Something bad turning out good", "A surprise gift", "A hidden mistake"], answer: 1 },
  { question: "Choose the correctly spelled word", options: ["accomodate", "accommodate", "acommodate", "acomodate"], answer: 1 },
  { question: "Synonym of BENEVOLENT", options: ["cruel", "kind", "selfish", "rough"], answer: 1 },
  { question: "Antonym of OPTIMISTIC", options: ["hopeful", "pessimistic", "cheerful", "positive"], answer: 1 },
  { question: "Fill: She is good ___ painting.", options: ["in", "at", "on", "with"], answer: 1 },
  { question: "Choose the correct sentence", options: ["Neither he nor I am responsible.", "Neither he nor I are responsible.", "Neither he or I am responsible.", "Neither he nor me am responsible."], answer: 0 },
  { question: "Idiom: 'Once in a blue moon' means", options: ["Often", "Never", "Very rarely", "Daily"], answer: 2 },
  { question: "Synonym of FRUGAL", options: ["wasteful", "thrifty", "rich", "easy"], answer: 1 },
  { question: "Antonym of TRANSPARENT", options: ["clear", "open", "opaque", "honest"], answer: 2 },
  { question: "Fill: He has been working ___ morning.", options: ["from", "since", "for", "at"], answer: 1 },
  { question: "Idiom: 'Hit the nail on the head' means", options: ["To hammer a nail", "To say exactly the right thing", "To miss the point", "To hurt yourself"], answer: 1 },
  { question: "Choose the correct sentence", options: ["He is one of the best player.", "He is one of the best players.", "He is one of best player.", "He is one of best players."], answer: 1 },
  { question: "Synonym of ARDUOUS", options: ["easy", "difficult", "soft", "small"], answer: 1 },
  { question: "Antonym of SCARCE", options: ["rare", "limited", "abundant", "small"], answer: 2 },
  { question: "Choose the correctly spelled word", options: ["seperate", "separate", "saparate", "seperete"], answer: 1 },
  { question: "Idiom: 'Spill the beans' means", options: ["Drop food", "Reveal a secret", "Cook well", "Make a mess"], answer: 1 },
  { question: "Fill: The book ___ on the table is mine.", options: ["lying", "laying", "lay", "lied"], answer: 0 },
  { question: "Synonym of EMPHASIZE", options: ["ignore", "stress", "remove", "agree"], answer: 1 },
  { question: "Antonym of GENUINE", options: ["real", "true", "fake", "honest"], answer: 2 },
  { question: "Choose the correct sentence", options: ["Less people came than expected.", "Fewer people came than expected.", "Fewer people came then expected.", "Less people come than expected."], answer: 1 },
  { question: "Idiom: 'Burn the midnight oil' means", options: ["Sleep early", "Work late at night", "Waste fuel", "Cause a fire"], answer: 1 },
  { question: "Synonym of VIVID", options: ["dull", "bright", "boring", "weak"], answer: 1 },
];

const englishHard = [
  { question: "Synonym of QUIXOTIC", options: ["practical", "idealistic but impractical", "dangerous", "lucky"], answer: 1 },
  { question: "Antonym of EPHEMERAL", options: ["short-lived", "permanent", "fragile", "weak"], answer: 1 },
  { question: "Synonym of OBFUSCATE", options: ["clarify", "confuse", "explain", "highlight"], answer: 1 },
  { question: "Antonym of LACONIC", options: ["brief", "verbose", "calm", "quiet"], answer: 1 },
  { question: "Idiom: 'Pyrrhic victory' means", options: ["A great win", "A win with devastating losses", "A surprise victory", "A moral victory"], answer: 1 },
  { question: "Choose the correct sentence", options: ["I would like to lay down for an hour.", "I would like to lie down for an hour.", "I would like to laid down for an hour.", "I would like to lay myself down for an hour."], answer: 1 },
  { question: "Synonym of UBIQUITOUS", options: ["rare", "found everywhere", "ancient", "useful"], answer: 1 },
  { question: "Antonym of MAGNANIMOUS", options: ["generous", "kind", "petty", "noble"], answer: 2 },
  { question: "Identify the figure of speech: 'Time is a thief.'", options: ["Simile", "Metaphor", "Hyperbole", "Personification"], answer: 1 },
  { question: "Synonym of CIRCUMSPECT", options: ["careless", "cautious", "rude", "rapid"], answer: 1 },
  { question: "Antonym of TACITURN", options: ["silent", "talkative", "calm", "rude"], answer: 1 },
  { question: "Idiom: 'A fly in the ointment' means", options: ["A small problem spoiling something", "A useful insect", "A rare event", "A medical issue"], answer: 0 },
  { question: "Synonym of PERSPICACIOUS", options: ["dull", "perceptive", "easy-going", "loud"], answer: 1 },
  { question: "Antonym of SANGUINE", options: ["cheerful", "hopeful", "gloomy", "active"], answer: 2 },
  { question: "Choose the correctly spelled word", options: ["mischievious", "mischievous", "mischevious", "mischeevous"], answer: 1 },
  { question: "Idiom: 'Albatross around one's neck' means", options: ["A heavy burden", "A blessing", "A close friend", "A challenge"], answer: 0 },
  { question: "Synonym of GARRULOUS", options: ["silent", "talkative", "shy", "rude"], answer: 1 },
  { question: "Antonym of PROFLIGATE", options: ["wasteful", "extravagant", "frugal", "rich"], answer: 2 },
  { question: "Identify: 'He is as brave as a lion.' is a", options: ["Metaphor", "Simile", "Personification", "Onomatopoeia"], answer: 1 },
  { question: "Synonym of RECALCITRANT", options: ["compliant", "stubborn", "honest", "modest"], answer: 1 },
  { question: "Antonym of ENERVATE", options: ["weaken", "exhaust", "energize", "tire"], answer: 2 },
  { question: "Idiom: 'Throw down the gauntlet' means", options: ["To surrender", "To issue a challenge", "To make a mistake", "To celebrate"], answer: 1 },
  { question: "Synonym of MELLIFLUOUS", options: ["harsh", "smooth and sweet sounding", "rough", "weak"], answer: 1 },
  { question: "Antonym of OSTENTATIOUS", options: ["showy", "modest", "loud", "wealthy"], answer: 1 },
  { question: "Choose the correctly punctuated sentence", options: ["She said 'I am tired'.", "She said, \"I am tired.\"", "She said: I am tired.", "She said \"I am tired\"."], answer: 1 },
];

// ----------------------------- CSE CORE -----------------------------
const cseEasy = [
  { question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Process Utility", "Common Processing Unit"], answer: 0 },
  { question: "RAM is", options: ["non-volatile", "volatile", "permanent storage", "secondary storage"], answer: 1 },
  { question: "Which is an OOP language?", options: ["C", "Java", "COBOL", "Assembly"], answer: 1 },
  { question: "HTML is used for", options: ["styling pages", "logic on server", "structure of web pages", "database design"], answer: 2 },
  { question: "Which data structure uses LIFO?", options: ["Queue", "Stack", "Linked List", "Tree"], answer: 1 },
  { question: "Binary 1010 in decimal is", options: ["8", "10", "12", "14"], answer: 1 },
  { question: "Which is a primary key property?", options: ["Can be null", "Must be unique", "Can repeat", "Optional"], answer: 1 },
  { question: "TCP is which type of protocol?", options: ["connectionless", "connection-oriented", "broadcast", "wireless"], answer: 1 },
  { question: "Operating system is a", options: ["application software", "system software", "utility program", "language compiler"], answer: 1 },
  { question: "SQL command to fetch data is", options: ["GET", "SELECT", "FETCH", "OPEN"], answer: 1 },
  { question: "ASCII value of 'A' is", options: ["64", "65", "97", "100"], answer: 1 },
  { question: "Which loop runs at least once?", options: ["for", "while", "do-while", "if-else"], answer: 2 },
  { question: "Which is a non-linear data structure?", options: ["Array", "Stack", "Queue", "Tree"], answer: 3 },
  { question: "Default access modifier in Java class member is", options: ["public", "private", "protected", "package-private"], answer: 3 },
  { question: "Time complexity of accessing array element by index is", options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"], answer: 0 },
  { question: "Which is NOT an HTTP method?", options: ["GET", "POST", "FETCH", "PUT"], answer: 2 },
  { question: "DBMS stands for", options: ["Data Base Management System", "Digital Base Memory System", "Data Backup Memory Storage", "Direct Base Management Server"], answer: 0 },
  { question: "1 KB equals", options: ["1000 bits", "1024 bytes", "1024 bits", "1000 bytes"], answer: 1 },
  { question: "Which of the following is a compiled language?", options: ["Python", "JavaScript", "C", "Bash"], answer: 2 },
  { question: "RGB stands for", options: ["Red Green Blue", "Real Graphic Build", "Random Graphical Bit", "Refresh Graphic Buffer"], answer: 0 },
  { question: "Which is a relational DBMS?", options: ["MongoDB", "MySQL", "Redis", "Cassandra"], answer: 1 },
  { question: "Which is the smallest unit of data?", options: ["Byte", "Bit", "Nibble", "Word"], answer: 1 },
  { question: "Which company developed Java?", options: ["Microsoft", "Sun (Oracle)", "Google", "Apple"], answer: 1 },
  { question: "IP address version with 32 bits is", options: ["IPv4", "IPv6", "MAC", "DNS"], answer: 0 },
  { question: "Which key uniquely identifies a row in a table?", options: ["Foreign key", "Primary key", "Candidate key", "Secondary key"], answer: 1 },
];

const cseModerate = [
  { question: "Worst-case time complexity of QuickSort is", options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], answer: 2 },
  { question: "BFS uses which data structure?", options: ["Stack", "Queue", "Heap", "Tree"], answer: 1 },
  { question: "Which OS scheduling can cause starvation?", options: ["FCFS", "Round Robin", "Priority", "Shortest Job First (always)"], answer: 2 },
  { question: "Normal form requiring no transitive dependency is", options: ["1NF", "2NF", "3NF", "BCNF"], answer: 2 },
  { question: "Which TCP/IP layer handles routing?", options: ["Application", "Transport", "Internet", "Link"], answer: 2 },
  { question: "Heap sort time complexity is", options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], answer: 0 },
  { question: "Inorder traversal of a BST gives", options: ["random order", "ascending sorted", "descending sorted", "preorder"], answer: 1 },
  { question: "Page replacement that gives the optimal hit ratio is", options: ["FIFO", "LRU", "Optimal (Belady)", "Random"], answer: 2 },
  { question: "Which join returns rows present in both tables?", options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL OUTER JOIN"], answer: 2 },
  { question: "DNS uses which port number by default?", options: ["21", "22", "53", "80"], answer: 2 },
  { question: "In Java, which keyword prevents inheritance?", options: ["static", "final", "private", "sealed"], answer: 1 },
  { question: "Which is a divide and conquer algorithm?", options: ["Bubble sort", "Linear search", "Merge sort", "Selection sort"], answer: 2 },
  { question: "Process state when waiting for I/O completion is", options: ["ready", "running", "blocked", "new"], answer: 2 },
  { question: "Which SQL clause filters groups?", options: ["WHERE", "ORDER BY", "HAVING", "GROUP BY"], answer: 2 },
  { question: "OSI layer responsible for end-to-end delivery is", options: ["Network", "Transport", "Data Link", "Session"], answer: 1 },
  { question: "Which traversal would visit a tree's root first?", options: ["Inorder", "Preorder", "Postorder", "Level-order only"], answer: 1 },
  { question: "Which is true about a Java interface?", options: ["Can have constructors", "Variables are final and static by default", "Methods are private by default", "Cannot be implemented"], answer: 1 },
  { question: "Which page replacement is impossible to implement perfectly?", options: ["LRU", "FIFO", "Optimal", "MRU"], answer: 2 },
  { question: "Time complexity of binary search on n elements is", options: ["O(n)", "O(n log n)", "O(log n)", "O(1)"], answer: 2 },
  { question: "Default port for HTTPS is", options: ["80", "443", "21", "8080"], answer: 1 },
  { question: "Which SQL command removes all rows but keeps structure?", options: ["DROP", "DELETE", "TRUNCATE", "REMOVE"], answer: 2 },
  { question: "Banker's algorithm is used for", options: ["scheduling", "deadlock avoidance", "memory allocation", "synchronization"], answer: 1 },
  { question: "In a hash table with chaining, average search complexity is", options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"], answer: 0 },
  { question: "Which of these is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"], answer: 2 },
  { question: "A race condition occurs due to", options: ["deadlock", "uncoordinated access to shared resource", "starvation", "thrashing"], answer: 1 },
];

const cseHard = [
  { question: "Time complexity of finding LCA in a balanced BST is", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 1 },
  { question: "Which algorithm finds shortest path with negative weights but no negative cycles?", options: ["Dijkstra", "BFS", "Bellman-Ford", "Floyd-Warshall only"], answer: 2 },
  { question: "Strassen's matrix multiplication has complexity", options: ["O(n^2)", "O(n^3)", "O(n^2.81)", "O(n log n)"], answer: 2 },
  { question: "Which scheduler manages long-term processes?", options: ["short-term", "long-term", "medium-term", "I/O"], answer: 1 },
  { question: "BCNF is stricter than", options: ["1NF only", "2NF only", "3NF only", "all of 1NF, 2NF, 3NF"], answer: 3 },
  { question: "Which is NOT a property of a transaction (ACID)?", options: ["Atomicity", "Consistency", "Isolation", "Distribution"], answer: 3 },
  { question: "Which problem is NP-complete?", options: ["sorting", "binary search", "Travelling Salesman (decision)", "matrix multiplication"], answer: 2 },
  { question: "Pumping Lemma is used to prove a language is NOT", options: ["context-free", "regular", "context-sensitive", "decidable"], answer: 1 },
  { question: "Number of TCP connection states is", options: ["6", "8", "10", "11"], answer: 3 },
  { question: "Inversion count of array using merge sort runs in", options: ["O(n)", "O(n^2)", "O(n log n)", "O(log n)"], answer: 2 },
  { question: "Which CPU scheduling minimizes average waiting time (theoretically)?", options: ["FCFS", "Round Robin", "Shortest Job First", "Priority"], answer: 2 },
  { question: "Which algorithm uses dynamic programming?", options: ["Quick sort", "Merge sort", "Floyd-Warshall", "Heap sort"], answer: 2 },
  { question: "Two-phase locking ensures", options: ["serializability", "deadlock-freedom", "fairness", "starvation-freedom"], answer: 0 },
  { question: "Which language is recognized by a deterministic PDA but not by a finite automaton?", options: ["a^n", "a^n b^n", "(ab)*", "any regular language"], answer: 1 },
  { question: "Which protocol is connectionless?", options: ["TCP", "UDP", "FTP", "SSH"], answer: 1 },
  { question: "Bloom filter trades correctness for", options: ["space and false positives", "time and accuracy", "memory and time", "none"], answer: 0 },
  { question: "Number of distinct BSTs with n=4 keys is (Catalan)", options: ["10", "14", "20", "24"], answer: 1 },
  { question: "Which of the following is true for a Red-Black tree height?", options: ["O(n)", "O(sqrt n)", "O(log n)", "O(log^2 n)"], answer: 2 },
  { question: "Worst-case complexity of Floyd-Warshall is", options: ["O(V^2)", "O(V^3)", "O(VE)", "O(E log V)"], answer: 1 },
  { question: "Which OS technique avoids fragmentation by using fixed-size blocks?", options: ["segmentation", "paging", "swapping", "compaction"], answer: 1 },
  { question: "B+ tree is used in DBMS primarily for", options: ["caching", "indexing", "compression", "logging"], answer: 1 },
  { question: "Which is true about REST?", options: ["stateful by design", "uses SOAP envelope", "uses HTTP verbs", "always uses XML"], answer: 2 },
  { question: "Asymptotic complexity of solving N-Queens by backtracking is", options: ["O(N!)", "O(N^2)", "O(2^N)", "O(N log N)"], answer: 0 },
  { question: "Page table size for 32-bit virtual address with 4 KB pages depends on", options: ["bus width only", "RAM size only", "page-table-entry size", "CPU cores"], answer: 2 },
  { question: "Which protocol uses public-key cryptography for key exchange?", options: ["MD5", "AES", "Diffie-Hellman", "SHA-256"], answer: 2 },
];

function tag(arr, category, difficulty) {
  return arr.map((q, idx) => ({ ...q, category, difficulty, bankIndex: idx }));
}

const allQuestions = [
  ...tag(aptitudeEasy,    "aptitude", "easy"),
  ...tag(aptitudeModerate,"aptitude", "moderate"),
  ...tag(aptitudeHard,    "aptitude", "hard"),
  ...tag(englishEasy,     "english",  "easy"),
  ...tag(englishModerate, "english",  "moderate"),
  ...tag(englishHard,     "english",  "hard"),
  ...tag(cseEasy,         "cseCore",  "easy"),
  ...tag(cseModerate,     "cseCore",  "moderate"),
  ...tag(cseHard,         "cseCore",  "hard"),
];

module.exports = allQuestions;
