// Question bank for IGIT Connect mock-test platform.
// 3 categories x 3 difficulties x 75 questions = 675 total.
// Each entry: { question, options: [4 strings], answer: index 0..3, category, difficulty }
// 5 mock tests per difficulty x 15 per category = 45 per test, all unique across the 5 tests.

// ----------------------------- APTITUDE -----------------------------
const aptitudeEasy = [
  { question: "What is 25% of 200?", options: ["25", "40", "50", "75"], answer: 2 },
  { question: "The average of 4, 8 and 12 is", options: ["6", "7", "8", "10"], answer: 2 },
  { question: "If a pen costs Rs. 12, what do 7 pens cost?", options: ["Rs. 72", "Rs. 84", "Rs. 96", "Rs. 100"], answer: 1 },
  { question: "Simple interest on Rs. 1000 at 10% per annum for 2 years is", options: ["Rs. 100", "Rs. 200", "Rs. 250", "Rs. 300"], answer: 1 },
  { question: "Which is the smallest fraction: 2/3, 3/5, 4/7, 5/9?", options: ["2/3", "3/5", "4/7", "5/9"], answer: 3 },
  { question: "If x + 5 = 12, what is x?", options: ["5", "6", "7", "8"], answer: 2 },
  { question: "The ratio of 2 hours to 30 minutes is", options: ["2:1", "4:1", "6:1", "8:1"], answer: 1 },
  { question: "How many seconds are there in 3 hours?", options: ["7200", "10800", "12000", "18000"], answer: 1 },
  { question: "If 4x = 36, then x =", options: ["6", "7", "8", "9"], answer: 3 },
  { question: "Square root of 144 is", options: ["10", "11", "12", "14"], answer: 2 },
  { question: "20% of 50 is equal to", options: ["8", "10", "12", "15"], answer: 1 },
  { question: "A train travels 60 km in 1 hour. Its speed in m/s is approximately", options: ["15", "16.67", "20", "25"], answer: 1 },
  { question: "Sum of angles in a triangle is", options: ["90 deg", "120 deg", "180 deg", "360 deg"], answer: 2 },
  { question: "Which number is prime?", options: ["9", "15", "21", "23"], answer: 3 },
  { question: "The next number in 2, 4, 8, 16, ___ is", options: ["20", "24", "32", "64"], answer: 2 },
  { question: "If 5 pencils cost Rs. 25, the cost of 8 pencils is", options: ["Rs. 35", "Rs. 40", "Rs. 45", "Rs. 50"], answer: 1 },
  { question: "Cube of 4 is", options: ["12", "16", "32", "64"], answer: 3 },
  { question: "LCM of 4 and 6 is", options: ["6", "10", "12", "24"], answer: 2 },
  { question: "HCF of 12 and 18 is", options: ["3", "4", "6", "9"], answer: 2 },
  { question: "If A:B = 2:3 and B:C = 4:5, then A:C =", options: ["6:5", "8:15", "8:5", "2:5"], answer: 1 },
  { question: "30% of x = 60. What is x?", options: ["100", "150", "180", "200"], answer: 3 },
  { question: "What comes next: 1, 4, 9, 16, ___?", options: ["20", "23", "25", "27"], answer: 2 },
  { question: "Half of 1/4 is", options: ["1/2", "1/3", "1/6", "1/8"], answer: 3 },
  { question: "Perimeter of a square with side 5 cm is", options: ["10 cm", "15 cm", "20 cm", "25 cm"], answer: 2 },
  { question: "If today is Monday, the day after 100 days will be", options: ["Tuesday", "Wednesday", "Thursday", "Friday"], answer: 1 },
  { question: "What is 75% of 80?", options: ["50", "55", "60", "65"], answer: 2 },
  { question: "If 3x = 27, then x =", options: ["6", "8", "9", "10"], answer: 2 },
  { question: "Sum of 1 to 10 is", options: ["45", "50", "55", "60"], answer: 2 },
  { question: "How many minutes are there in 4 hours?", options: ["120", "180", "240", "300"], answer: 2 },
  { question: "Average of 10, 20, 30 is", options: ["15", "20", "25", "30"], answer: 1 },
  { question: "If 2x + 4 = 14, x =", options: ["3", "4", "5", "6"], answer: 2 },
  { question: "What is 10% of 250?", options: ["20", "25", "30", "35"], answer: 1 },
  { question: "Square of 11 is", options: ["111", "121", "131", "141"], answer: 1 },
  { question: "Cube root of 27 is", options: ["2", "3", "4", "5"], answer: 1 },
  { question: "Which is greater: 1/2 or 1/3?", options: ["1/2", "1/3", "Equal", "Cannot say"], answer: 0 },
  { question: "Number of sides in a hexagon", options: ["4", "5", "6", "7"], answer: 2 },
  { question: "Area of rectangle with sides 4 and 5 is", options: ["9", "12", "20", "25"], answer: 2 },
  { question: "If 5x = 40, then x =", options: ["6", "7", "8", "9"], answer: 2 },
  { question: "Half of 50 is", options: ["20", "25", "30", "40"], answer: 1 },
  { question: "Double of 17 is", options: ["32", "34", "36", "38"], answer: 1 },
  { question: "What comes next: 5, 10, 15, 20, ___?", options: ["22", "23", "24", "25"], answer: 3 },
  { question: "If pencil is Rs 5, cost of 6 pencils is", options: ["Rs 25", "Rs 28", "Rs 30", "Rs 32"], answer: 2 },
  { question: "1 hour = ___ seconds", options: ["360", "600", "3600", "6000"], answer: 2 },
  { question: "Sum of even numbers from 2 to 10 is", options: ["20", "25", "30", "35"], answer: 2 },
  { question: "If x - 7 = 3, then x =", options: ["8", "9", "10", "11"], answer: 2 },
  { question: "1 dozen equals", options: ["10", "12", "14", "16"], answer: 1 },
  { question: "Square root of 169 is", options: ["11", "12", "13", "14"], answer: 2 },
  { question: "If A=2, B=4, C=6, then D = ?", options: ["7", "8", "9", "10"], answer: 1 },
  { question: "20 + 30 + 40 = ?", options: ["80", "85", "90", "95"], answer: 2 },
  { question: "The smallest 2-digit prime is", options: ["10", "11", "13", "17"], answer: 1 },
  { question: "If 6x = 48, x =", options: ["6", "7", "8", "9"], answer: 2 },
  { question: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: 2 },
  { question: "What is 50% of 1000?", options: ["100", "250", "500", "750"], answer: 2 },
  { question: "Number of months with 31 days", options: ["5", "6", "7", "8"], answer: 2 },
  { question: "Average of 5 and 15 is", options: ["8", "10", "12", "15"], answer: 1 },
  { question: "If x + x = 24, then x =", options: ["10", "12", "14", "16"], answer: 1 },
  { question: "1 km equals how many meters?", options: ["100", "500", "1000", "10000"], answer: 2 },
  { question: "10 multiplied by 9 is", options: ["80", "90", "100", "110"], answer: 1 },
  { question: "What is 30% of 60?", options: ["12", "15", "18", "21"], answer: 2 },
  { question: "Square of 9 is", options: ["72", "81", "90", "99"], answer: 1 },
  { question: "If a clock shows 3:00, angle between hands is", options: ["60", "75", "90", "120"], answer: 2 },
  { question: "If price increases from 100 to 120, % increase is", options: ["10%", "15%", "20%", "25%"], answer: 2 },
  { question: "Numbers divisible by 4 in 1-20", options: ["3", "4", "5", "6"], answer: 2 },
  { question: "What number when added to 18 gives 25?", options: ["5", "6", "7", "8"], answer: 2 },
  { question: "1 minute = ___ seconds", options: ["30", "45", "60", "90"], answer: 2 },
  { question: "Largest 1-digit prime number", options: ["3", "5", "7", "9"], answer: 2 },
  { question: "Smallest natural number is", options: ["0", "1", "2", "10"], answer: 1 },
  { question: "If train runs at 50 km/h, in 2 hours it covers", options: ["50 km", "75 km", "100 km", "150 km"], answer: 2 },
  { question: "How many wheels in 5 cars (4-wheelers)?", options: ["15", "18", "20", "22"], answer: 2 },
  { question: "Which is the smallest fraction: 1/2, 1/3, 1/4, 1/5?", options: ["1/2", "1/3", "1/4", "1/5"], answer: 3 },
  { question: "Rs 100 split equally among 4 people gives each", options: ["Rs 20", "Rs 25", "Rs 30", "Rs 50"], answer: 1 },
  { question: "30 - 12 = ?", options: ["12", "16", "18", "20"], answer: 2 },
  { question: "5 squared is", options: ["10", "20", "25", "30"], answer: 2 },
  { question: "What is 1/4 of 100?", options: ["20", "25", "40", "50"], answer: 1 },
  { question: "Decimal of 1/2 is", options: ["0.2", "0.25", "0.5", "0.75"], answer: 2 },
];

const aptitudeModerate = [
  { question: "A man buys an article for Rs. 200 and sells it for Rs. 250. His profit % is", options: ["20%", "25%", "30%", "40%"], answer: 1 },
  { question: "Two trains, 100m and 80m long, travel in opposite directions at 36 and 54 km/h. Time to cross each other is", options: ["6.4 s", "7.2 s", "8.0 s", "9.0 s"], answer: 1 },
  { question: "Compound interest on Rs. 5000 at 10% p.a. for 2 years is", options: ["Rs. 1000", "Rs. 1050", "Rs. 1100", "Rs. 1150"], answer: 1 },
  { question: "The average age of 5 boys is 12 years. If a 6th boy aged 18 joins, new average is", options: ["12", "13", "14", "15"], answer: 1 },
  { question: "If 8 men finish a job in 12 days, 12 men will finish it in", options: ["6 days", "8 days", "10 days", "16 days"], answer: 1 },
  { question: "A boat goes 30 km upstream in 5 h and 30 km downstream in 3 h. Stream speed is", options: ["1 km/h", "2 km/h", "3 km/h", "4 km/h"], answer: 1 },
  { question: "Selling at Rs. 480, a shopkeeper loses 20%. Cost price is", options: ["Rs. 540", "Rs. 580", "Rs. 600", "Rs. 640"], answer: 2 },
  { question: "If x^2 - 5x + 6 = 0, the roots are", options: ["1, 6", "2, 3", "-2, -3", "1, 5"], answer: 1 },
  { question: "Mean of 10 numbers is 20. If 25 and 35 are removed, new mean is", options: ["17.5", "18", "18.75", "20"], answer: 0 },
  { question: "Pipe A fills a tank in 10 min, B in 15 min. Together they fill it in", options: ["5 min", "6 min", "7 min", "8 min"], answer: 1 },
  { question: "A sum doubles in 8 years at simple interest. Rate is", options: ["10%", "12%", "12.5%", "15%"], answer: 2 },
  { question: "Which is greater: 2^3, 3^2, 5^1?", options: ["2^3", "3^2", "5^1", "All equal"], answer: 1 },
  { question: "If sin theta = 1/2, theta in degrees is", options: ["30", "45", "60", "90"], answer: 0 },
  { question: "A clock loses 5 minutes every hour. After 12 hours, it shows time behind by", options: ["30 min", "45 min", "60 min", "75 min"], answer: 2 },
  { question: "P and Q started a business with Rs. 5000 and Rs. 7500. Profit ratio is", options: ["1:2", "2:3", "5:7", "5:8"], answer: 1 },
  { question: "Discount of 15% on a Rs. 800 article gives selling price", options: ["Rs. 600", "Rs. 660", "Rs. 680", "Rs. 720"], answer: 2 },
  { question: "Average of first 5 multiples of 7 is", options: ["14", "17.5", "21", "28"], answer: 2 },
  { question: "A number, when doubled and reduced by 8, equals 30. The number is", options: ["17", "18", "19", "21"], answer: 2 },
  { question: "If 60% of A = 75% of B, then A:B is", options: ["3:4", "4:5", "5:4", "9:10"], answer: 2 },
  { question: "Probability of getting at least one head in 2 coin tosses is", options: ["1/4", "1/2", "3/4", "1"], answer: 2 },
  { question: "A man covers 3 km in 30 minutes. His speed in km/h is", options: ["3", "4", "5", "6"], answer: 3 },
  { question: "Successive discounts of 10% and 20% are equivalent to a single discount of", options: ["25%", "27%", "28%", "30%"], answer: 2 },
  { question: "If radius of a circle is doubled, area becomes", options: ["2x", "3x", "4x", "8x"], answer: 2 },
  { question: "Sum of first 20 natural numbers is", options: ["190", "200", "210", "220"], answer: 2 },
  { question: "If a:b = 3:4 and b:c = 8:9, then a:b:c =", options: ["3:4:9", "6:8:9", "12:16:18", "9:12:16"], answer: 1 },
  { question: "A car travels 240 km in 4 hours. Average speed is", options: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"], answer: 2 },
  { question: "Profit of 25% on cost Rs 200 gives selling price", options: ["Rs 220", "Rs 240", "Rs 250", "Rs 260"], answer: 2 },
  { question: "Three numbers in ratio 2:3:5 add to 100. Largest is", options: ["20", "30", "40", "50"], answer: 3 },
  { question: "If x + y = 10 and x - y = 4, then x =", options: ["5", "6", "7", "8"], answer: 2 },
  { question: "Time to fill a tank with two pipes at 6 and 12 hours each is", options: ["3 h", "4 h", "5 h", "6 h"], answer: 1 },
  { question: "Average of first 10 odd numbers is", options: ["8", "9", "10", "11"], answer: 2 },
  { question: "If 30% of x = 90, then x =", options: ["200", "250", "300", "350"], answer: 2 },
  { question: "Selling price Rs 600, profit 20%. Cost price is", options: ["Rs 480", "Rs 500", "Rs 520", "Rs 550"], answer: 1 },
  { question: "Compound interest on Rs 4000 at 5% for 2 years is", options: ["Rs 410", "Rs 415", "Rs 420", "Rs 425"], answer: 0 },
  { question: "If 12 men finish a job in 18 days, 9 men finish it in", options: ["20 days", "22 days", "24 days", "27 days"], answer: 2 },
  { question: "Probability of getting an even number on a die is", options: ["1/4", "1/3", "1/2", "2/3"], answer: 2 },
  { question: "x and y share Rs 1500 in ratio 2:3. y gets", options: ["Rs 600", "Rs 750", "Rs 900", "Rs 1000"], answer: 2 },
  { question: "If sin 30° + cos 60° equals", options: ["0.5", "1", "1.5", "2"], answer: 1 },
  { question: "20% increase followed by 20% decrease results in net change", options: ["0%", "-2%", "-4%", "-5%"], answer: 2 },
  { question: "First and last term of an AP are 3 and 27, common diff 4. Number of terms is", options: ["5", "6", "7", "8"], answer: 2 },
  { question: "Average speed for 60 km at 20 km/h and 60 km at 30 km/h is", options: ["22 km/h", "24 km/h", "25 km/h", "26 km/h"], answer: 1 },
  { question: "If 2x + 3y = 12 and x + y = 5, then x =", options: ["2", "3", "4", "5"], answer: 1 },
  { question: "Boat speed in still water 10 km/h, current 2 km/h. Downstream speed is", options: ["8 km/h", "10 km/h", "12 km/h", "14 km/h"], answer: 2 },
  { question: "A loses 10% then sells at Rs 450. CP was", options: ["Rs 460", "Rs 480", "Rs 500", "Rs 520"], answer: 2 },
  { question: "Sum of first 50 natural numbers is", options: ["1225", "1250", "1275", "1300"], answer: 2 },
  { question: "If 4 cows eat 4 bales in 4 days, 8 cows eat 8 bales in", options: ["2 days", "4 days", "6 days", "8 days"], answer: 1 },
  { question: "% by which 25 is more than 20", options: ["20%", "25%", "30%", "33%"], answer: 1 },
  { question: "GCD of 36 and 60 is", options: ["6", "8", "12", "18"], answer: 2 },
  { question: "If log 2 = 0.301, log 8 =", options: ["0.602", "0.778", "0.903", "1.000"], answer: 2 },
  { question: "Roots of x² − 7x + 12 = 0 are", options: ["2, 6", "3, 4", "1, 12", "−3, −4"], answer: 1 },
  { question: "If A is 30% more than B, then B is what % less than A", options: ["20%", "23%", "25%", "30%"], answer: 1 },
  { question: "A train 200m long crosses a pole in 10s. Speed in km/h is", options: ["54", "60", "72", "80"], answer: 2 },
  { question: "Average of 5 numbers is 30. After adding 6th, average is 32. 6th number is", options: ["30", "38", "40", "42"], answer: 3 },
  { question: "If radius doubles, volume of sphere becomes", options: ["2x", "4x", "6x", "8x"], answer: 3 },
  { question: "Time to cover 60 km at 40 km/h", options: ["1 h", "1.25 h", "1.5 h", "1.75 h"], answer: 2 },
  { question: "x² = 144, then x = ?", options: ["±10", "±11", "±12", "±13"], answer: 2 },
  { question: "20 boys + 30 girls in class; % of girls is", options: ["50%", "55%", "60%", "65%"], answer: 2 },
  { question: "If interest is Rs 200 on Rs 1000 at 5%, time is", options: ["2 yrs", "3 yrs", "4 yrs", "5 yrs"], answer: 2 },
  { question: "Probability of drawing a heart from 52 cards is", options: ["1/13", "1/4", "1/2", "13/52"], answer: 1 },
  { question: "Tan 45° equals", options: ["0", "1/2", "1", "√3"], answer: 2 },
  { question: "If a student got 60% in an exam of 200 marks, marks scored", options: ["100", "110", "120", "130"], answer: 2 },
  { question: "Sum of angles in a quadrilateral", options: ["180°", "270°", "360°", "540°"], answer: 2 },
  { question: "Area of circle with radius 7 (use π=22/7)", options: ["144", "150", "154", "164"], answer: 2 },
  { question: "If 25% of x is 50, then x is", options: ["100", "150", "200", "250"], answer: 2 },
  { question: "A train 100m long takes 5 sec to cross a pole. Speed in m/s", options: ["10", "15", "20", "25"], answer: 2 },
  { question: "If price increases 10% then 10%, net increase is", options: ["20%", "21%", "22%", "25%"], answer: 1 },
  { question: "If 3 cats catch 3 mice in 3 minutes, 100 cats in 100 minutes catch", options: ["3", "100", "300", "1000"], answer: 1 },
  { question: "If x:y = 5:7 and y:z = 14:5, then x:z is", options: ["1:1", "2:1", "5:5", "7:1"], answer: 1 },
  { question: "Sum of 4 consecutive integers is 70. Smallest is", options: ["15", "16", "17", "18"], answer: 1 },
  { question: "If a number is increased by 50%, ratio of new to old is", options: ["2:3", "3:2", "1:2", "5:3"], answer: 1 },
  { question: "Difference between SI and CI on Rs 1000 at 10% for 2 years", options: ["Rs 5", "Rs 10", "Rs 15", "Rs 20"], answer: 1 },
  { question: "Number of integer solutions of |x| ≤ 5 is", options: ["9", "10", "11", "12"], answer: 2 },
  { question: "If 8x = 56, then x =", options: ["6", "7", "8", "9"], answer: 1 },
  { question: "Volume of cube with edge 4 cm is", options: ["32", "48", "56", "64"], answer: 3 },
  { question: "If clock shows 6:00, angle between hands is", options: ["90°", "120°", "150°", "180°"], answer: 3 },
];

const aptitudeHard = [
  { question: "From a pack of 52 cards, probability of drawing a king or a heart is", options: ["1/13", "4/13", "16/52", "17/52"], answer: 1 },
  { question: "How many ways can the letters of MISSISSIPPI be arranged?", options: ["34650", "39916800", "40320", "11!/4!"], answer: 0 },
  { question: "A number is divisible by 6 and 8 but not 5. Smallest such positive integer is", options: ["24", "48", "72", "120"], answer: 0 },
  { question: "If log10 2 = 0.301, then log10 5 ≈", options: ["0.602", "0.699", "0.778", "0.845"], answer: 1 },
  { question: "Three pipes A, B, C fill a tank in 6, 8, 12 hours. Together they fill in", options: ["8/3 h", "24/9 h", "8/9 h", "2 h"], answer: 0 },
  { question: "Sum of an infinite GP with a=4, r=1/2 is", options: ["6", "7", "8", "10"], answer: 2 },
  { question: "Number of ways to seat 5 people around a round table is", options: ["120", "60", "24", "240"], answer: 2 },
  { question: "60% acid mixed with 30% acid forms 4 L of 50% solution. Volume of 60% solution is", options: ["1.5 L", "2 L", "2.67 L", "3 L"], answer: 2 },
  { question: "If P(A)=0.4, P(B)=0.5 and A,B independent, P(A∩B) =", options: ["0.1", "0.2", "0.4", "0.9"], answer: 1 },
  { question: "Number of trailing zeros in 100! is", options: ["20", "22", "24", "25"], answer: 2 },
  { question: "If x = 3+2*sqrt(2), then x + 1/x =", options: ["4", "5", "6", "8"], answer: 2 },
  { question: "Sides of a triangle are 7, 8, 9. Its area (Heron's formula) ≈", options: ["24.0", "26.83", "28.0", "30.0"], answer: 1 },
  { question: "If a, b, c are in HP and a=2, c=6, then b =", options: ["3", "3.5", "4", "5"], answer: 0 },
  { question: "20 men complete a job in 24 days at 8 h/day. To finish in 20 days at 6 h/day, men needed =", options: ["28", "30", "32", "36"], answer: 2 },
  { question: "Roots of x^2 + 4x + 5 = 0 are", options: ["real distinct", "real equal", "complex conjugates", "rational"], answer: 2 },
  { question: "Number of diagonals in a regular polygon with 10 sides is", options: ["20", "25", "35", "45"], answer: 2 },
  { question: "From 6 boys and 4 girls, a committee of 5 with at least 2 girls. Number of ways =", options: ["120", "186", "246", "300"], answer: 2 },
  { question: "Limit as x→0 of (sin 3x)/x equals", options: ["0", "1", "3", "infinite"], answer: 2 },
  { question: "Volume of a sphere of radius 6 cm is (in cm^3)", options: ["288 pi", "216 pi", "144 pi", "904 pi"], answer: 0 },
  { question: "If 2^x = 32 and 3^y = 81, then x + y =", options: ["7", "8", "9", "10"], answer: 2 },
  { question: "How many integers between 1 and 1000 are divisible by 7 but not by 3?", options: ["95", "96", "100", "143"], answer: 1 },
  { question: "Area enclosed by y = x^2, y = 4 is", options: ["16/3", "32/3", "8", "16"], answer: 1 },
  { question: "Standard deviation of 2, 4, 4, 4, 5, 5, 7, 9 is", options: ["1.5", "2", "2.45", "3"], answer: 1 },
  { question: "Number of solutions of |x-2| + |x+3| = 5 in real numbers is", options: ["1", "2", "infinite", "0"], answer: 2 },
  { question: "If A = ((1,2),(3,4)), determinant of A is", options: ["-2", "0", "2", "10"], answer: 0 },
  { question: "Number of ways to choose 4 from 9 is", options: ["84", "126", "210", "252"], answer: 1 },
  { question: "If z = 1+i, then |z|² is", options: ["1", "2", "√2", "2√2"], answer: 1 },
  { question: "Limit of (1+1/n)^n as n→∞", options: ["1", "e", "π", "∞"], answer: 1 },
  { question: "Sum of an AP: 3+7+11+...+99", options: ["1275", "1326", "1350", "1428"], answer: 1 },
  { question: "If sin x = 0.6, cos x =", options: ["0.4", "0.6", "0.8", "1.0"], answer: 2 },
  { question: "How many 4-digit numbers with no repetition can be formed from 1,2,3,4,5?", options: ["60", "120", "240", "625"], answer: 1 },
  { question: "GCD of 252 and 105", options: ["7", "14", "21", "28"], answer: 2 },
  { question: "Number of solutions of x² + y² = 25 in integers", options: ["8", "12", "16", "20"], answer: 1 },
  { question: "Median of 3, 7, 8, 11, 13", options: ["7", "8", "9", "10"], answer: 1 },
  { question: "Variance of 1,2,3,4,5", options: ["1", "1.5", "2", "2.5"], answer: 2 },
  { question: "If a, b roots of x²-5x+6=0, then a²+b²", options: ["13", "17", "25", "37"], answer: 0 },
  { question: "Number of ways to arrange BANANA letters", options: ["60", "90", "120", "180"], answer: 0 },
  { question: "Probability of all heads in 5 tosses", options: ["1/16", "1/32", "1/64", "1/128"], answer: 1 },
  { question: "Slope of line 3x + 4y = 12 is", options: ["-3/4", "3/4", "-4/3", "4/3"], answer: 0 },
  { question: "Determinant of identity matrix of size n is", options: ["0", "1", "n", "n!"], answer: 1 },
  { question: "If P(A)=0.3, P(B)=0.5, P(A∪B)=0.6, then P(A∩B)", options: ["0.1", "0.2", "0.3", "0.4"], answer: 1 },
  { question: "Sum of cubes of first 5 natural numbers", options: ["100", "200", "225", "250"], answer: 2 },
  { question: "Number of distinct factors of 360", options: ["20", "22", "24", "30"], answer: 2 },
  { question: "Permutations of 'CAT'", options: ["3", "6", "9", "12"], answer: 1 },
  { question: "If ω is cube root of unity, 1+ω+ω² =", options: ["0", "1", "2", "3"], answer: 0 },
  { question: "Coefficient of x³ in (1+x)^5", options: ["5", "10", "15", "20"], answer: 1 },
  { question: "Inverse of 3 mod 7 is", options: ["3", "4", "5", "6"], answer: 2 },
  { question: "Number of zeros at end of 25!", options: ["4", "5", "6", "7"], answer: 2 },
  { question: "If f(x)=x², then f'(3) =", options: ["3", "6", "9", "12"], answer: 1 },
  { question: "Integral of 1/x is", options: ["ln|x|+C", "x²/2+C", "x+C", "1+C"], answer: 0 },
  { question: "Eccentricity of circle is", options: ["0", "1", "<1", ">1"], answer: 0 },
  { question: "Number of edges in K5 (complete graph on 5)", options: ["8", "9", "10", "12"], answer: 2 },
  { question: "Pigeonhole principle: 13 items in 12 boxes guarantees ≥", options: ["1", "2", "3", "13"], answer: 1 },
  { question: "Limit of sin(x)/x as x→0", options: ["0", "1", "∞", "Undefined"], answer: 1 },
  { question: "Sum of first 10 squares (1²+2²+...)", options: ["385", "395", "405", "420"], answer: 0 },
  { question: "If x² + y² + z² = 14 and x+y+z=6, find xy+yz+zx", options: ["10", "11", "12", "13"], answer: 1 },
  { question: "Roots of x²+x+1=0 are", options: ["Real distinct", "Real equal", "Complex conjugate", "Rational"], answer: 2 },
  { question: "Prime factorization of 360", options: ["2³·3²·5", "2²·3²·5", "2³·3·5", "2²·3·5²"], answer: 0 },
  { question: "Probability that a leap year has 53 Sundays", options: ["1/7", "2/7", "3/7", "1/2"], answer: 1 },
  { question: "Number of diagonals in pentagon", options: ["5", "7", "9", "10"], answer: 0 },
  { question: "If 4 dice are rolled, P(sum = 6)", options: ["10/1296", "15/1296", "20/1296", "35/1296"], answer: 0 },
  { question: "How many ways to color 4 sides of square with 3 colors?", options: ["12", "21", "24", "81"], answer: 1 },
  { question: "Order of group Z6 is", options: ["3", "5", "6", "12"], answer: 2 },
  { question: "Number of bipartite graphs on 4 vertices", options: ["10", "20", "41", "70"], answer: 2 },
  { question: "If A is invertible, det(A⁻¹)·det(A)", options: ["0", "1", "-1", "Depends"], answer: 1 },
  { question: "Convergence of geometric series 1+r+r²+... if |r|<1 sums to", options: ["1/r", "1/(1-r)", "r/(1-r)", "1+r"], answer: 1 },
  { question: "Mean of binomial(n,p)", options: ["np", "p", "n", "p(1-p)"], answer: 0 },
  { question: "Pascal triangle 5th row middle entry", options: ["6", "10", "15", "20"], answer: 1 },
  { question: "If matrix A is orthogonal, det(A) =", options: ["0", "±1", "1 only", "Any real"], answer: 1 },
  { question: "Solutions of cos(x)=0 in [0,2π]", options: ["1", "2", "3", "4"], answer: 1 },
  { question: "Number of integers in [1,100] divisible by 5 or 7", options: ["28", "32", "34", "37"], answer: 1 },
  { question: "Probability of drawing 2 aces from deck without replacement", options: ["1/13·1/17", "12/52·11/51", "4/52·3/51", "1/52"], answer: 2 },
  { question: "If logₐ b = 3, log_b a =", options: ["1/3", "3", "0", "9"], answer: 0 },
  { question: "Number of ways to put 5 different balls in 3 distinct boxes", options: ["3⁵", "5³", "5!", "15"], answer: 0 },
  { question: "Trace of identity matrix of size 4", options: ["1", "2", "4", "16"], answer: 2 },
];

// ----------------------------- ENGLISH -----------------------------
const englishEasy = [
  { question: "Synonym of HAPPY", options: ["sad", "joyful", "angry", "tired"], answer: 1 },
  { question: "Antonym of BEGIN", options: ["start", "open", "end", "go"], answer: 2 },
  { question: "Choose correctly spelled word", options: ["recieve", "receive", "receeve", "recive"], answer: 1 },
  { question: "Plural of CHILD", options: ["childs", "childes", "children", "childrens"], answer: 2 },
  { question: "Past tense of GO", options: ["goed", "went", "gone", "going"], answer: 1 },
  { question: "Article needed: ___ apple a day keeps the doctor away.", options: ["A", "An", "The", "No article"], answer: 1 },
  { question: "Synonym of BIG", options: ["tiny", "huge", "narrow", "weak"], answer: 1 },
  { question: "Antonym of FAST", options: ["quick", "rapid", "slow", "swift"], answer: 2 },
  { question: "Choose the correct sentence", options: ["He don't like tea.", "He doesn't likes tea.", "He doesn't like tea.", "He didn't likes tea."], answer: 2 },
  { question: "Synonym of START", options: ["finish", "begin", "stop", "halt"], answer: 1 },
  { question: "Antonym of HOT", options: ["warm", "cool", "cold", "boiling"], answer: 2 },
  { question: "Past tense of EAT", options: ["eated", "ate", "eaten", "eating"], answer: 1 },
  { question: "Plural of MOUSE (animal)", options: ["mouses", "mice", "mouse", "meeces"], answer: 1 },
  { question: "Choose the noun: She runs fast.", options: ["She", "runs", "fast", "none"], answer: 0 },
  { question: "Choose the verb: The dog barks loudly.", options: ["The", "dog", "barks", "loudly"], answer: 2 },
  { question: "Antonym of OPEN", options: ["unlock", "shut", "wide", "loose"], answer: 1 },
  { question: "Synonym of SMART", options: ["dumb", "clever", "rude", "rough"], answer: 1 },
  { question: "Article: He is ___ honest man.", options: ["a", "an", "the", "no article"], answer: 1 },
  { question: "Past tense of WRITE", options: ["writed", "wrote", "written", "writing"], answer: 1 },
  { question: "Antonym of TRUE", options: ["honest", "real", "false", "right"], answer: 2 },
  { question: "Synonym of QUICK", options: ["fast", "slow", "lazy", "long"], answer: 0 },
  { question: "Plural of LEAF", options: ["leafs", "leaves", "leafes", "leavs"], answer: 1 },
  { question: "Choose the adjective: The red car is fast.", options: ["The", "red", "car", "is"], answer: 1 },
  { question: "Past tense of BUY", options: ["buyed", "bought", "buyt", "buying"], answer: 1 },
  { question: "Antonym of EASY", options: ["simple", "soft", "hard", "smooth"], answer: 2 },
  { question: "Synonym of CLEVER", options: ["dull", "smart", "lazy", "weak"], answer: 1 },
  { question: "Antonym of NEW", options: ["fresh", "old", "modern", "young"], answer: 1 },
  { question: "Plural of FOOT", options: ["foots", "feet", "footes", "feets"], answer: 1 },
  { question: "Past tense of RUN", options: ["runned", "ran", "ranned", "running"], answer: 1 },
  { question: "Article: I saw ___ owl on the tree.", options: ["a", "an", "the", "no article"], answer: 1 },
  { question: "Synonym of LOUD", options: ["quiet", "noisy", "soft", "calm"], answer: 1 },
  { question: "Antonym of LIGHT (weight)", options: ["bright", "dark", "heavy", "small"], answer: 2 },
  { question: "Choose the correct sentence", options: ["She have a dog.", "She has a dog.", "She had a dog yesterday everyday.", "She have had a dog."], answer: 1 },
  { question: "Past tense of SEE", options: ["seed", "saw", "seen", "seeing"], answer: 1 },
  { question: "Synonym of TIRED", options: ["energetic", "exhausted", "happy", "active"], answer: 1 },
  { question: "Antonym of YOUNG", options: ["new", "fresh", "old", "small"], answer: 2 },
  { question: "Plural of TOOTH", options: ["toothes", "tooths", "teeth", "toothies"], answer: 2 },
  { question: "Past tense of MAKE", options: ["maked", "made", "make", "making"], answer: 1 },
  { question: "Article: He plays ___ guitar.", options: ["a", "an", "the", "no article"], answer: 2 },
  { question: "Synonym of BRAVE", options: ["coward", "scared", "courageous", "weak"], answer: 2 },
  { question: "Antonym of RICH", options: ["wealthy", "poor", "kind", "famous"], answer: 1 },
  { question: "Choose noun: The book is on the table.", options: ["The", "is", "book", "on"], answer: 2 },
  { question: "Past tense of TAKE", options: ["took", "taken", "taked", "taking"], answer: 0 },
  { question: "Plural of STORY", options: ["storys", "stories", "storyes", "story"], answer: 1 },
  { question: "Synonym of BEGIN", options: ["finish", "start", "stop", "end"], answer: 1 },
  { question: "Antonym of WET", options: ["damp", "soaked", "dry", "moist"], answer: 2 },
  { question: "Choose the verb: Mary sings beautifully.", options: ["Mary", "sings", "beautifully", "none"], answer: 1 },
  { question: "Past tense of READ", options: ["readed", "read", "redd", "reading"], answer: 1 },
  { question: "Article: ___ University of Mumbai", options: ["a", "an", "the", "no article"], answer: 2 },
  { question: "Synonym of ANGRY", options: ["happy", "furious", "calm", "joyful"], answer: 1 },
  { question: "Antonym of UP", options: ["over", "down", "high", "above"], answer: 1 },
  { question: "Plural of CITY", options: ["citys", "cities", "cityes", "citty"], answer: 1 },
  { question: "Past tense of GIVE", options: ["gived", "gave", "given", "giving"], answer: 1 },
  { question: "Synonym of CALM", options: ["angry", "peaceful", "loud", "tired"], answer: 1 },
  { question: "Antonym of LOVE", options: ["like", "hate", "care", "want"], answer: 1 },
  { question: "Choose adjective: A beautiful flower bloomed.", options: ["A", "beautiful", "flower", "bloomed"], answer: 1 },
  { question: "Past tense of SLEEP", options: ["sleeped", "slept", "sleep", "sleeping"], answer: 1 },
  { question: "Article: ___ Eiffel Tower is in Paris.", options: ["A", "An", "The", "No article"], answer: 2 },
  { question: "Synonym of FUNNY", options: ["sad", "boring", "humorous", "rude"], answer: 2 },
  { question: "Antonym of DAY", options: ["night", "dawn", "noon", "evening"], answer: 0 },
  { question: "Plural of WOMAN", options: ["womans", "womens", "women", "womes"], answer: 2 },
  { question: "Past tense of THINK", options: ["thinked", "thought", "thinking", "thunk"], answer: 1 },
  { question: "Synonym of RICH", options: ["poor", "wealthy", "tired", "weak"], answer: 1 },
  { question: "Antonym of LATE", options: ["slow", "early", "fast", "delayed"], answer: 1 },
  { question: "Choose pronoun: She gave it to him.", options: ["gave", "She", "to", "the"], answer: 1 },
  { question: "Past tense of FLY", options: ["flied", "flew", "flown", "flying"], answer: 1 },
  { question: "Article: ___ honest answer", options: ["A", "An", "The", "No article"], answer: 1 },
  { question: "Synonym of STRONG", options: ["weak", "powerful", "soft", "small"], answer: 1 },
  { question: "Antonym of WIN", options: ["succeed", "lose", "play", "draw"], answer: 1 },
  { question: "Plural of BOX", options: ["boxs", "boxes", "boxen", "boxies"], answer: 1 },
  { question: "Past tense of SPEAK", options: ["speaked", "spoke", "spoken", "speaking"], answer: 1 },
  { question: "Synonym of OLD", options: ["young", "ancient", "modern", "fresh"], answer: 1 },
  { question: "Antonym of CLEAN", options: ["pure", "neat", "dirty", "shiny"], answer: 2 },
  { question: "Choose adverb: She sings loudly.", options: ["She", "sings", "loudly", "none"], answer: 2 },
  { question: "Past tense of BRING", options: ["bringed", "brought", "broughten", "bringing"], answer: 1 },
];

const englishModerate = [
  { question: "Idiom: 'Bury the hatchet' means", options: ["Hide a weapon", "Make peace", "Start a fight", "Lose interest"], answer: 1 },
  { question: "Synonym of DILIGENT", options: ["lazy", "hardworking", "careless", "rude"], answer: 1 },
  { question: "Antonym of CONCEAL", options: ["hide", "reveal", "cover", "mask"], answer: 1 },
  { question: "Idiom: 'A blessing in disguise' means", options: ["A hidden curse", "Something bad turning out good", "A surprise gift", "A hidden mistake"], answer: 1 },
  { question: "Choose the correctly spelled word", options: ["accomodate", "accommodate", "acommodate", "acomodate"], answer: 1 },
  { question: "Synonym of BENEVOLENT", options: ["cruel", "kind", "selfish", "rough"], answer: 1 },
  { question: "Antonym of OPTIMISTIC", options: ["hopeful", "pessimistic", "cheerful", "positive"], answer: 1 },
  { question: "Fill: She is good ___ painting.", options: ["in", "at", "on", "with"], answer: 1 },
  { question: "Choose the correct sentence", options: ["Neither he nor I am responsible.", "Neither he nor I are responsible.", "Neither he or I am responsible.", "Neither he nor me am responsible."], answer: 0 },
  { question: "Idiom: 'Once in a blue moon' means", options: ["Often", "Never", "Very rarely", "Daily"], answer: 2 },
  { question: "Synonym of FRUGAL", options: ["wasteful", "thrifty", "rich", "easy"], answer: 1 },
  { question: "Antonym of TRANSPARENT", options: ["clear", "open", "opaque", "honest"], answer: 2 },
  { question: "Fill: He has been working ___ morning.", options: ["from", "since", "for", "at"], answer: 1 },
  { question: "Idiom: 'Hit the nail on the head' means", options: ["To hammer a nail", "To say exactly the right thing", "To miss the point", "To hurt yourself"], answer: 1 },
  { question: "Choose the correct sentence", options: ["He is one of the best player.", "He is one of the best players.", "He is one of best player.", "He is one of best players."], answer: 1 },
  { question: "Synonym of ARDUOUS", options: ["easy", "difficult", "soft", "small"], answer: 1 },
  { question: "Antonym of SCARCE", options: ["rare", "limited", "abundant", "small"], answer: 2 },
  { question: "Choose the correctly spelled word", options: ["seperate", "separate", "saparate", "seperete"], answer: 1 },
  { question: "Idiom: 'Spill the beans' means", options: ["Drop food", "Reveal a secret", "Cook well", "Make a mess"], answer: 1 },
  { question: "Fill: The book ___ on the table is mine.", options: ["lying", "laying", "lay", "lied"], answer: 0 },
  { question: "Synonym of EMPHASIZE", options: ["ignore", "stress", "remove", "agree"], answer: 1 },
  { question: "Antonym of GENUINE", options: ["real", "true", "fake", "honest"], answer: 2 },
  { question: "Choose the correct sentence", options: ["Less people came than expected.", "Fewer people came than expected.", "Fewer people came then expected.", "Less people come than expected."], answer: 1 },
  { question: "Idiom: 'Burn the midnight oil' means", options: ["Sleep early", "Work late at night", "Waste fuel", "Cause a fire"], answer: 1 },
  { question: "Synonym of VIVID", options: ["dull", "bright", "boring", "weak"], answer: 1 },
  { question: "Idiom: 'Cost an arm and a leg' means", options: ["Painful", "Very expensive", "Cheap", "Free"], answer: 1 },
  { question: "Synonym of OBSOLETE", options: ["modern", "outdated", "useful", "trendy"], answer: 1 },
  { question: "Antonym of ABUNDANT", options: ["plentiful", "rich", "scarce", "huge"], answer: 2 },
  { question: "Idiom: 'Piece of cake' means", options: ["Difficult", "Easy", "Tasty", "Sweet"], answer: 1 },
  { question: "Choose the correctly spelled word", options: ["embarass", "embarrass", "embarras", "embarrasss"], answer: 1 },
  { question: "Synonym of FACILITATE", options: ["hinder", "ease", "stop", "delay"], answer: 1 },
  { question: "Antonym of CONFINED", options: ["restricted", "limited", "free", "narrow"], answer: 2 },
  { question: "Fill: He insists ___ paying the bill.", options: ["in", "on", "for", "at"], answer: 1 },
  { question: "Choose the correct sentence", options: ["I have lived here since 5 years.", "I have lived here for 5 years.", "I am living here since 5 years.", "I lived here for 5 years."], answer: 1 },
  { question: "Idiom: 'Break the ice' means", options: ["Start a fight", "Initiate conversation", "Cool down", "Be cold"], answer: 1 },
  { question: "Synonym of LUCRATIVE", options: ["losing", "profitable", "expensive", "cheap"], answer: 1 },
  { question: "Antonym of MEAGER", options: ["small", "scarce", "abundant", "tight"], answer: 2 },
  { question: "Fill: He apologized ___ his behavior.", options: ["of", "for", "with", "on"], answer: 1 },
  { question: "Idiom: 'Cut corners' means", options: ["Take shortcuts (often poorly)", "Bend metal", "Trim fabric", "Avoid"], answer: 0 },
  { question: "Choose the correctly spelled word", options: ["acheive", "achieve", "acheeve", "atcheive"], answer: 1 },
  { question: "Synonym of TRIVIAL", options: ["important", "unimportant", "huge", "central"], answer: 1 },
  { question: "Antonym of FERTILE", options: ["productive", "rich", "barren", "abundant"], answer: 2 },
  { question: "Fill: She is allergic ___ peanuts.", options: ["of", "to", "with", "from"], answer: 1 },
  { question: "Idiom: 'Beat around the bush' means", options: ["Hit something", "Avoid the main topic", "Search hard", "Work outside"], answer: 1 },
  { question: "Choose the correct sentence", options: ["He is taller than me.", "He is taller than I.", "He is more taller than me.", "Both A and B"], answer: 3 },
  { question: "Synonym of REPRIMAND", options: ["praise", "scold", "thank", "support"], answer: 1 },
  { question: "Antonym of PROHIBIT", options: ["forbid", "ban", "allow", "restrict"], answer: 2 },
  { question: "Fill: The team consists ___ ten players.", options: ["from", "off", "of", "with"], answer: 2 },
  { question: "Idiom: 'Put all eggs in one basket' means", options: ["Concentrate resources in one place (risky)", "Carry eggs", "Plan carefully", "Help others"], answer: 0 },
  { question: "Choose correctly spelled", options: ["beleive", "believe", "beleeve", "believ"], answer: 1 },
  { question: "Synonym of CANDID", options: ["dishonest", "frank", "shy", "rude"], answer: 1 },
  { question: "Antonym of LENIENT", options: ["soft", "mild", "strict", "kind"], answer: 2 },
  { question: "Fill: I am fond ___ chocolates.", options: ["with", "of", "for", "in"], answer: 1 },
  { question: "Idiom: 'On cloud nine' means", options: ["Sad", "Extremely happy", "Confused", "Tired"], answer: 1 },
  { question: "Synonym of DETER", options: ["encourage", "deter, discourage", "discourage", "promote"], answer: 2 },
  { question: "Choose the correctly punctuated", options: ["He said , 'Good morning'.", "He said 'Good morning'.", "He said, \"Good morning.\"", "He said \"Good morning\"."], answer: 2 },
  { question: "Antonym of DEPRIVE", options: ["take", "remove", "give", "deny"], answer: 2 },
  { question: "Fill: He recovered ___ his illness.", options: ["from", "off", "with", "to"], answer: 0 },
  { question: "Idiom: 'Steal someone's thunder' means", options: ["Steal sound", "Take credit for someone's idea", "Make noise", "Be sneaky"], answer: 1 },
  { question: "Synonym of RESILIENT", options: ["weak", "tough", "soft", "weary"], answer: 1 },
  { question: "Antonym of GREGARIOUS", options: ["sociable", "outgoing", "reclusive", "kind"], answer: 2 },
  { question: "Choose the correct sentence", options: ["The team is playing well.", "The team are playing well.", "Both correct depending on context", "Neither"], answer: 2 },
  { question: "Synonym of TENACIOUS", options: ["weak", "persistent", "lazy", "rough"], answer: 1 },
  { question: "Antonym of HOSTILE", options: ["unfriendly", "aggressive", "friendly", "rude"], answer: 2 },
  { question: "Fill: He is engrossed ___ his work.", options: ["in", "on", "with", "from"], answer: 0 },
  { question: "Idiom: 'Read between the lines' means", options: ["Find hidden meaning", "Read aloud", "Read fast", "Read textbooks"], answer: 0 },
  { question: "Synonym of INDIFFERENT", options: ["caring", "uninterested", "kind", "active"], answer: 1 },
  { question: "Antonym of GLOOMY", options: ["dark", "sad", "cheerful", "dim"], answer: 2 },
  { question: "Fill: She is junior ___ him.", options: ["from", "to", "than", "of"], answer: 1 },
  { question: "Idiom: 'Caught red-handed' means", options: ["Caught with red gloves", "Caught in the act", "Embarrassed", "Hurt"], answer: 1 },
  { question: "Synonym of AMBIGUOUS", options: ["clear", "unclear", "easy", "long"], answer: 1 },
  { question: "Antonym of ARROGANT", options: ["proud", "haughty", "humble", "rude"], answer: 2 },
  { question: "Choose the correct preposition: She is fond ___ music.", options: ["with", "of", "in", "for"], answer: 1 },
  { question: "Synonym of SCRUTINIZE", options: ["ignore", "examine", "skip", "praise"], answer: 1 },
  { question: "Antonym of FUTILE", options: ["useless", "vain", "useful", "empty"], answer: 2 },
];

const englishHard = [
  { question: "Synonym of QUIXOTIC", options: ["practical", "idealistic but impractical", "dangerous", "lucky"], answer: 1 },
  { question: "Antonym of EPHEMERAL", options: ["short-lived", "permanent", "fragile", "weak"], answer: 1 },
  { question: "Synonym of OBFUSCATE", options: ["clarify", "confuse", "explain", "highlight"], answer: 1 },
  { question: "Antonym of LACONIC", options: ["brief", "verbose", "calm", "quiet"], answer: 1 },
  { question: "Idiom: 'Pyrrhic victory' means", options: ["A great win", "A win with devastating losses", "A surprise victory", "A moral victory"], answer: 1 },
  { question: "Choose the correct sentence", options: ["I would like to lay down for an hour.", "I would like to lie down for an hour.", "I would like to laid down for an hour.", "I would like to lay myself down for an hour."], answer: 1 },
  { question: "Synonym of UBIQUITOUS", options: ["rare", "found everywhere", "ancient", "useful"], answer: 1 },
  { question: "Antonym of MAGNANIMOUS", options: ["generous", "kind", "petty", "noble"], answer: 2 },
  { question: "Identify the figure of speech: 'Time is a thief.'", options: ["Simile", "Metaphor", "Hyperbole", "Personification"], answer: 1 },
  { question: "Synonym of CIRCUMSPECT", options: ["careless", "cautious", "rude", "rapid"], answer: 1 },
  { question: "Antonym of TACITURN", options: ["silent", "talkative", "calm", "rude"], answer: 1 },
  { question: "Idiom: 'A fly in the ointment' means", options: ["A small problem spoiling something", "A useful insect", "A rare event", "A medical issue"], answer: 0 },
  { question: "Synonym of PERSPICACIOUS", options: ["dull", "perceptive", "easy-going", "loud"], answer: 1 },
  { question: "Antonym of SANGUINE", options: ["cheerful", "hopeful", "gloomy", "active"], answer: 2 },
  { question: "Choose the correctly spelled word", options: ["mischievious", "mischievous", "mischevious", "mischeevous"], answer: 1 },
  { question: "Idiom: 'Albatross around one's neck' means", options: ["A heavy burden", "A blessing", "A close friend", "A challenge"], answer: 0 },
  { question: "Synonym of GARRULOUS", options: ["silent", "talkative", "shy", "rude"], answer: 1 },
  { question: "Antonym of PROFLIGATE", options: ["wasteful", "extravagant", "frugal", "rich"], answer: 2 },
  { question: "Identify: 'He is as brave as a lion.' is a", options: ["Metaphor", "Simile", "Personification", "Onomatopoeia"], answer: 1 },
  { question: "Synonym of RECALCITRANT", options: ["compliant", "stubborn", "honest", "modest"], answer: 1 },
  { question: "Antonym of ENERVATE", options: ["weaken", "exhaust", "energize", "tire"], answer: 2 },
  { question: "Idiom: 'Throw down the gauntlet' means", options: ["To surrender", "To issue a challenge", "To make a mistake", "To celebrate"], answer: 1 },
  { question: "Synonym of MELLIFLUOUS", options: ["harsh", "smooth and sweet sounding", "rough", "weak"], answer: 1 },
  { question: "Antonym of OSTENTATIOUS", options: ["showy", "modest", "loud", "wealthy"], answer: 1 },
  { question: "Choose the correctly punctuated sentence", options: ["She said 'I am tired'.", "She said, \"I am tired.\"", "She said: I am tired.", "She said \"I am tired\"."], answer: 1 },
  { question: "Synonym of CACOPHONY", options: ["harmony", "discordant noise", "silence", "music"], answer: 1 },
  { question: "Antonym of LUCID", options: ["clear", "obvious", "obscure", "bright"], answer: 2 },
  { question: "Idiom: 'Bite the bullet' means", options: ["Eat metal", "Endure pain or difficulty", "Be aggressive", "Misfire"], answer: 1 },
  { question: "Synonym of NEFARIOUS", options: ["good", "wicked", "noble", "brave"], answer: 1 },
  { question: "Antonym of SUCCINCT", options: ["concise", "brief", "verbose", "sweet"], answer: 2 },
  { question: "Idiom: 'Beard the lion in his den' means", options: ["Hunt", "Confront a powerful person on their territory", "Be brave", "Avoid danger"], answer: 1 },
  { question: "Choose the correct sentence", options: ["Either of the boys are coming.", "Either of the boys is coming.", "Either of the boy are coming.", "Either of the boy is coming."], answer: 1 },
  { question: "Synonym of EQUIVOCAL", options: ["clear", "ambiguous", "decisive", "honest"], answer: 1 },
  { question: "Antonym of PROLIX", options: ["wordy", "verbose", "concise", "tiresome"], answer: 2 },
  { question: "Identify the figure of speech: 'The wind whispered through the trees.'", options: ["Metaphor", "Personification", "Simile", "Hyperbole"], answer: 1 },
  { question: "Synonym of EXACERBATE", options: ["soothe", "worsen", "calm", "fix"], answer: 1 },
  { question: "Antonym of ALACRITY", options: ["eagerness", "speed", "reluctance", "joy"], answer: 2 },
  { question: "Idiom: 'A wolf in sheep's clothing' means", options: ["A disguise", "A dangerous person disguised as harmless", "An animal", "A liar"], answer: 1 },
  { question: "Choose the correctly spelled word", options: ["concious", "conscious", "consious", "conshious"], answer: 1 },
  { question: "Synonym of PUERILE", options: ["mature", "childish", "wise", "rough"], answer: 1 },
  { question: "Antonym of INDOLENT", options: ["lazy", "idle", "industrious", "quiet"], answer: 2 },
  { question: "Idiom: 'Crocodile tears' means", options: ["Real tears", "Insincere display of emotion", "Animal tears", "Tears of joy"], answer: 1 },
  { question: "Synonym of SURREPTITIOUS", options: ["open", "secret", "honest", "loud"], answer: 1 },
  { question: "Antonym of EQUITABLE", options: ["fair", "just", "unfair", "balanced"], answer: 2 },
  { question: "Identify: 'The classroom was a zoo.'", options: ["Simile", "Metaphor", "Personification", "Onomatopoeia"], answer: 1 },
  { question: "Synonym of TRUCULENT", options: ["peaceful", "aggressive", "calm", "weak"], answer: 1 },
  { question: "Antonym of FRUGAL", options: ["thrifty", "saving", "extravagant", "rich"], answer: 2 },
  { question: "Idiom: 'Skeleton in the closet' means", options: ["A real skeleton", "Hidden secret or shame", "Bones", "Old clothes"], answer: 1 },
  { question: "Synonym of VICISSITUDE", options: ["stability", "change/fluctuation", "calm", "wealth"], answer: 1 },
  { question: "Antonym of PRAGMATIC", options: ["practical", "realistic", "idealistic", "useful"], answer: 2 },
  { question: "Choose the correct preposition: He acted ___ my advice.", options: ["with", "against", "on", "to"], answer: 1 },
  { question: "Synonym of INELUCTABLE", options: ["avoidable", "inevitable", "easy", "soft"], answer: 1 },
  { question: "Antonym of OBSEQUIOUS", options: ["servile", "fawning", "assertive", "humble"], answer: 2 },
  { question: "Idiom: 'Pour oil on troubled waters' means", options: ["Make worse", "Pacify a quarrel", "Cause a fire", "Be slick"], answer: 1 },
  { question: "Synonym of REPLETE", options: ["empty", "filled", "small", "weak"], answer: 1 },
  { question: "Antonym of CHARY", options: ["careful", "cautious", "careless", "wary"], answer: 2 },
  { question: "Choose the correct sentence", options: ["He prefers tea than coffee.", "He prefers tea to coffee.", "He prefers tea over coffee.", "Both B and C"], answer: 3 },
  { question: "Synonym of PROPITIOUS", options: ["unfortunate", "favorable", "harmful", "weak"], answer: 1 },
  { question: "Antonym of TURGID", options: ["swollen", "bombastic", "deflated", "rich"], answer: 2 },
  { question: "Idiom: 'Bell the cat' means", options: ["Tame an animal", "Take a risky step for the group", "Make noise", "Hide"], answer: 1 },
  { question: "Synonym of RECONDITE", options: ["obvious", "obscure", "easy", "small"], answer: 1 },
  { question: "Antonym of ASCETIC", options: ["austere", "self-denying", "indulgent", "kind"], answer: 2 },
  { question: "Choose the correctly spelled word", options: ["accomodation", "accommodation", "acommodation", "accommadation"], answer: 1 },
  { question: "Synonym of EBULLIENT", options: ["depressed", "exuberant", "calm", "rude"], answer: 1 },
  { question: "Antonym of QUIESCENT", options: ["calm", "still", "active", "quiet"], answer: 2 },
  { question: "Identify: 'The classroom was buzzing with activity.'", options: ["Metaphor", "Simile", "Onomatopoeia", "Personification"], answer: 0 },
  { question: "Synonym of CONTRITION", options: ["pride", "remorse", "joy", "courage"], answer: 1 },
  { question: "Antonym of PHILANTHROPIC", options: ["generous", "kind", "selfish", "noble"], answer: 2 },
  { question: "Choose the correct sentence", options: ["Each of the players have a uniform.", "Each of the players has a uniform.", "Each of the player has a uniform.", "Each of the players are having a uniform."], answer: 1 },
  { question: "Synonym of FECUND", options: ["barren", "fertile", "weak", "small"], answer: 1 },
  { question: "Antonym of VENERABLE", options: ["respected", "honored", "disreputable", "kind"], answer: 2 },
  { question: "Idiom: 'Let the cat out of the bag' means", options: ["Free a cat", "Reveal a secret", "Make trouble", "Buy a pet"], answer: 1 },
  { question: "Synonym of INSCRUTABLE", options: ["clear", "mysterious", "obvious", "easy"], answer: 1 },
  { question: "Antonym of EXTANT", options: ["existing", "alive", "extinct", "current"], answer: 2 },
  { question: "Identify: 'She was as quiet as a mouse.'", options: ["Metaphor", "Simile", "Personification", "Hyperbole"], answer: 1 },
];

// ----------------------------- CSE CORE -----------------------------
const cseEasy = [
  { question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Process Utility", "Common Processing Unit"], answer: 0 },
  { question: "RAM is", options: ["non-volatile", "volatile", "permanent storage", "secondary storage"], answer: 1 },
  { question: "Which is an OOP language?", options: ["C", "Java", "COBOL", "Assembly"], answer: 1 },
  { question: "HTML is used for", options: ["styling pages", "logic on server", "structure of web pages", "database design"], answer: 2 },
  { question: "Which data structure uses LIFO?", options: ["Queue", "Stack", "Linked List", "Tree"], answer: 1 },
  { question: "Binary 1010 in decimal is", options: ["8", "10", "12", "14"], answer: 1 },
  { question: "Which is a primary key property?", options: ["Can be null", "Must be unique", "Can repeat", "Optional"], answer: 1 },
  { question: "TCP is which type of protocol?", options: ["connectionless", "connection-oriented", "broadcast", "wireless"], answer: 1 },
  { question: "Operating system is a", options: ["application software", "system software", "utility program", "language compiler"], answer: 1 },
  { question: "SQL command to fetch data is", options: ["GET", "SELECT", "FETCH", "OPEN"], answer: 1 },
  { question: "ASCII value of 'A' is", options: ["64", "65", "97", "100"], answer: 1 },
  { question: "Which loop runs at least once?", options: ["for", "while", "do-while", "if-else"], answer: 2 },
  { question: "Which is a non-linear data structure?", options: ["Array", "Stack", "Queue", "Tree"], answer: 3 },
  { question: "Default access modifier in Java class member is", options: ["public", "private", "protected", "package-private"], answer: 3 },
  { question: "Time complexity of accessing array element by index is", options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"], answer: 0 },
  { question: "Which is NOT an HTTP method?", options: ["GET", "POST", "FETCH", "PUT"], answer: 2 },
  { question: "DBMS stands for", options: ["Data Base Management System", "Digital Base Memory System", "Data Backup Memory Storage", "Direct Base Management Server"], answer: 0 },
  { question: "1 KB equals", options: ["1000 bits", "1024 bytes", "1024 bits", "1000 bytes"], answer: 1 },
  { question: "Which of the following is a compiled language?", options: ["Python", "JavaScript", "C", "Bash"], answer: 2 },
  { question: "RGB stands for", options: ["Red Green Blue", "Real Graphic Build", "Random Graphical Bit", "Refresh Graphic Buffer"], answer: 0 },
  { question: "Which is a relational DBMS?", options: ["MongoDB", "MySQL", "Redis", "Cassandra"], answer: 1 },
  { question: "Which is the smallest unit of data?", options: ["Byte", "Bit", "Nibble", "Word"], answer: 1 },
  { question: "Which company developed Java?", options: ["Microsoft", "Sun (Oracle)", "Google", "Apple"], answer: 1 },
  { question: "IP address version with 32 bits is", options: ["IPv4", "IPv6", "MAC", "DNS"], answer: 0 },
  { question: "Which key uniquely identifies a row in a table?", options: ["Foreign key", "Primary key", "Candidate key", "Secondary key"], answer: 1 },
  { question: "Which is a markup language?", options: ["Java", "HTML", "C++", "Python"], answer: 1 },
  { question: "Which device stores data permanently?", options: ["RAM", "Cache", "Hard Disk", "Register"], answer: 2 },
  { question: "What is full form of URL?", options: ["Uniform Resource Locator", "Universal Resource Link", "Unified Resource Logger", "Unique Resource List"], answer: 0 },
  { question: "Default file extension for Python is", options: [".py", ".pyt", ".pyth", ".python"], answer: 0 },
  { question: "Which is NOT a programming language?", options: ["C", "Java", "HTML", "Python"], answer: 2 },
  { question: "What does HTTP stand for?", options: ["Hyper Text Transfer Protocol", "High Transfer Text Protocol", "Hyper Text Transit Protocol", "Hyper Transmission Text Protocol"], answer: 0 },
  { question: "Binary 1100 in decimal is", options: ["10", "12", "14", "16"], answer: 1 },
  { question: "Which is a search engine?", options: ["Chrome", "Google", "Firefox", "Edge"], answer: 1 },
  { question: "1 GB equals approximately", options: ["1000 KB", "1024 MB", "1024 KB", "100 MB"], answer: 1 },
  { question: "Which is a Linux distribution?", options: ["Windows 10", "Ubuntu", "macOS", "iOS"], answer: 1 },
  { question: "Which loop has fixed iterations?", options: ["for", "while", "do-while", "infinite"], answer: 0 },
  { question: "Which sorts in O(n²) average?", options: ["Bubble sort", "Merge sort", "Quick sort", "Heap sort"], answer: 0 },
  { question: "What is index of first array element?", options: ["-1", "0", "1", "2"], answer: 1 },
  { question: "What does GUI stand for?", options: ["Graphical User Interface", "General User Interface", "Graphics Unified Interface", "Group User Interface"], answer: 0 },
  { question: "RAM is", options: ["temporary", "permanent", "removable", "external"], answer: 0 },
  { question: "Which is an interpreted language?", options: ["C", "C++", "Python", "Pascal"], answer: 2 },
  { question: "Which company makes Windows OS?", options: ["Apple", "Google", "Microsoft", "IBM"], answer: 2 },
  { question: "Bit means", options: ["8 bytes", "Binary digit", "Binary table", "Big integer"], answer: 1 },
  { question: "Which is fastest memory?", options: ["RAM", "Cache", "ROM", "Hard Disk"], answer: 1 },
  { question: "Which protocol is used to send email?", options: ["HTTP", "FTP", "SMTP", "POP3"], answer: 2 },
  { question: "Which is a framework for JS?", options: ["React", "Linux", "Python", "Java"], answer: 0 },
  { question: "What does PDF stand for?", options: ["Portable Document Format", "Public Data File", "Personal Document Format", "Print Data File"], answer: 0 },
  { question: "Which is NOT a database?", options: ["MySQL", "MongoDB", "Apache", "PostgreSQL"], answer: 2 },
  { question: "Output of 5/2 in Python 3 is", options: ["2", "2.5", "3", "Error"], answer: 1 },
  { question: "What does XML stand for?", options: ["eXtensible Markup Language", "Extra Markup Language", "X-Mark Language", "eXtended Markup List"], answer: 0 },
  { question: "Which OSI layer deals with data delivery?", options: ["Physical", "Network", "Transport", "Application"], answer: 2 },
  { question: "Which device converts AC to DC?", options: ["Transformer", "Rectifier", "Inverter", "Generator"], answer: 1 },
  { question: "Which protocol is for file transfer?", options: ["HTTP", "FTP", "SMTP", "DNS"], answer: 1 },
  { question: "Which is FALSE about variables?", options: ["Stores data", "Has a name", "Has a fixed type always", "Can be reassigned"], answer: 2 },
  { question: "What is binary of 7?", options: ["110", "111", "100", "101"], answer: 1 },
  { question: "Which is a server-side language?", options: ["HTML", "CSS", "PHP", "JavaScript (browser)"], answer: 2 },
  { question: "What does CSS stand for?", options: ["Cascading Style Sheets", "Computer Style Sheet", "Creative Style System", "Custom Style Sheet"], answer: 0 },
  { question: "Which is a database language?", options: ["HTML", "SQL", "C", "Java"], answer: 1 },
  { question: "Which sorts is stable?", options: ["Quick sort", "Heap sort", "Merge sort", "Selection sort"], answer: 2 },
  { question: "Which is a virtual memory?", options: ["RAM", "ROM", "Swap space/disk", "Cache"], answer: 2 },
  { question: "Which is a graph traversal?", options: ["Bubble", "BFS", "Linear", "Quick"], answer: 1 },
  { question: "Which company makes Android?", options: ["Apple", "Google", "Samsung", "Microsoft"], answer: 1 },
  { question: "What is bit-rate?", options: ["Bits per second", "Bytes per second", "Bits stored", "Bit position"], answer: 0 },
  { question: "Which is volatile?", options: ["Hard Drive", "RAM", "ROM", "SSD"], answer: 1 },
  { question: "Which is NOT logical operator?", options: ["AND", "OR", "NOT", "ADD"], answer: 3 },
  { question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Language", "Standard Query Language", "System Query Logic"], answer: 0 },
  { question: "Which is the parent class in Java?", options: ["String", "Number", "Object", "Class"], answer: 2 },
  { question: "Which is a number system?", options: ["Decimal", "Binary", "Octal", "All of the above"], answer: 3 },
  { question: "What does API stand for?", options: ["Application Programming Interface", "Applied Program Interface", "Application Process Interaction", "App Process Integration"], answer: 0 },
  { question: "Which is fastest sorting on small data?", options: ["Insertion sort", "Bubble sort", "Selection sort", "Merge sort"], answer: 0 },
  { question: "Which symbol is used for assignment in C?", options: ["==", "=", ":=", "->"], answer: 1 },
  { question: "Which is true about array?", options: ["Same data type", "Different data type only", "Can be infinite", "Cannot be empty"], answer: 0 },
  { question: "What is full form of OOP?", options: ["Object Oriented Programming", "Order Of Programming", "Object Of Program", "Operations Of Program"], answer: 0 },
  { question: "Which year was Java released?", options: ["1990", "1995", "2000", "2005"], answer: 1 },
  { question: "Which is largest unit?", options: ["MB", "GB", "TB", "KB"], answer: 2 },
];

const cseModerate = [
  { question: "Worst-case time complexity of QuickSort is", options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], answer: 2 },
  { question: "BFS uses which data structure?", options: ["Stack", "Queue", "Heap", "Tree"], answer: 1 },
  { question: "Which OS scheduling can cause starvation?", options: ["FCFS", "Round Robin", "Priority", "Shortest Job First (always)"], answer: 2 },
  { question: "Normal form requiring no transitive dependency is", options: ["1NF", "2NF", "3NF", "BCNF"], answer: 2 },
  { question: "Which TCP/IP layer handles routing?", options: ["Application", "Transport", "Internet", "Link"], answer: 2 },
  { question: "Heap sort time complexity is", options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], answer: 0 },
  { question: "Inorder traversal of a BST gives", options: ["random order", "ascending sorted", "descending sorted", "preorder"], answer: 1 },
  { question: "Page replacement that gives the optimal hit ratio is", options: ["FIFO", "LRU", "Optimal (Belady)", "Random"], answer: 2 },
  { question: "Which join returns rows present in both tables?", options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL OUTER JOIN"], answer: 2 },
  { question: "DNS uses which port number by default?", options: ["21", "22", "53", "80"], answer: 2 },
  { question: "In Java, which keyword prevents inheritance?", options: ["static", "final", "private", "sealed"], answer: 1 },
  { question: "Which is a divide and conquer algorithm?", options: ["Bubble sort", "Linear search", "Merge sort", "Selection sort"], answer: 2 },
  { question: "Process state when waiting for I/O completion is", options: ["ready", "running", "blocked", "new"], answer: 2 },
  { question: "Which SQL clause filters groups?", options: ["WHERE", "ORDER BY", "HAVING", "GROUP BY"], answer: 2 },
  { question: "OSI layer responsible for end-to-end delivery is", options: ["Network", "Transport", "Data Link", "Session"], answer: 1 },
  { question: "Which traversal would visit a tree's root first?", options: ["Inorder", "Preorder", "Postorder", "Level-order only"], answer: 1 },
  { question: "Which is true about a Java interface?", options: ["Can have constructors", "Variables are final and static by default", "Methods are private by default", "Cannot be implemented"], answer: 1 },
  { question: "Which page replacement is impossible to implement perfectly?", options: ["LRU", "FIFO", "Optimal", "MRU"], answer: 2 },
  { question: "Time complexity of binary search on n elements is", options: ["O(n)", "O(n log n)", "O(log n)", "O(1)"], answer: 2 },
  { question: "Default port for HTTPS is", options: ["80", "443", "21", "8080"], answer: 1 },
  { question: "Which SQL command removes all rows but keeps structure?", options: ["DROP", "DELETE", "TRUNCATE", "REMOVE"], answer: 2 },
  { question: "Banker's algorithm is used for", options: ["scheduling", "deadlock avoidance", "memory allocation", "synchronization"], answer: 1 },
  { question: "In a hash table with chaining, average search complexity is", options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"], answer: 0 },
  { question: "Which of these is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"], answer: 2 },
  { question: "A race condition occurs due to", options: ["deadlock", "uncoordinated access to shared resource", "starvation", "thrashing"], answer: 1 },
  { question: "Best case of insertion sort is", options: ["O(n²)", "O(n)", "O(log n)", "O(1)"], answer: 1 },
  { question: "Tree with root and only one child per node forms", options: ["Binary tree", "Linked list", "AVL tree", "Heap"], answer: 1 },
  { question: "Which traversal uses stack?", options: ["BFS", "DFS", "Level order", "Inorder"], answer: 1 },
  { question: "Which port is used by SSH?", options: ["21", "22", "23", "25"], answer: 1 },
  { question: "Which is true about virtual memory?", options: ["Doesn't exist", "Allows running larger programs than RAM", "Same as RAM", "Faster than cache"], answer: 1 },
  { question: "Which DBMS principle ensures one's transaction does not affect another?", options: ["Atomicity", "Consistency", "Isolation", "Durability"], answer: 2 },
  { question: "Which is NOT a TCP feature?", options: ["Connection-oriented", "Reliable", "Connectionless", "Sequence numbers"], answer: 2 },
  { question: "What is in adjacency matrix for unconnected vertices?", options: ["1", "0", "−1", "Inf"], answer: 1 },
  { question: "Which DS is used for shortest path BFS?", options: ["Stack", "Queue", "Heap", "Tree"], answer: 1 },
  { question: "Default heap of Java priority queue is", options: ["Max heap", "Min heap", "AVL", "BST"], answer: 1 },
  { question: "Which protocol is used for IP address resolution?", options: ["DHCP", "ARP", "DNS", "FTP"], answer: 1 },
  { question: "How many comparisons in worst case for binary search of n items?", options: ["n", "log n", "n/2", "2n"], answer: 1 },
  { question: "Which is NOT in OOP?", options: ["Encapsulation", "Inheritance", "Polymorphism", "Compilation"], answer: 3 },
  { question: "DDL stands for", options: ["Data Definition Language", "Data Detail Language", "Database Definition Logic", "Data Direct Language"], answer: 0 },
  { question: "Which scheduling algorithm has highest CPU utilization?", options: ["FCFS", "SJF", "Round Robin", "Priority"], answer: 1 },
  { question: "What is foreign key?", options: ["Same as primary key", "References primary key of another table", "Always unique", "Always null"], answer: 1 },
  { question: "Which Layer is HTTP?", options: ["Network", "Transport", "Application", "Session"], answer: 2 },
  { question: "Cyclic redundancy check is for", options: ["Encryption", "Error detection", "Compression", "Routing"], answer: 1 },
  { question: "Which graph algorithm uses min-heap?", options: ["BFS", "DFS", "Dijkstra", "Prims (using heap)"], answer: 3 },
  { question: "What is normalization?", options: ["Reduce redundancy", "Increase redundancy", "Encrypt data", "Compress data"], answer: 0 },
  { question: "Cache memory is between", options: ["CPU and RAM", "RAM and Disk", "RAM and ROM", "Disk and DVD"], answer: 0 },
  { question: "Which traversal is left-root-right?", options: ["Preorder", "Inorder", "Postorder", "Level order"], answer: 1 },
  { question: "Which is symmetric crypto?", options: ["RSA", "DH", "AES", "Hash"], answer: 2 },
  { question: "Time complexity of inserting at head of linked list", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 0 },
  { question: "DML stands for", options: ["Data Modeling Language", "Data Manipulation Language", "Data Memory Language", "Data Module Language"], answer: 1 },
  { question: "Which is OS scheduling preemptive?", options: ["FCFS", "SJF (basic)", "Round Robin", "Priority (non-preemptive)"], answer: 2 },
  { question: "AVL tree balance factor max", options: ["0", "1", "2", "Any integer"], answer: 1 },
  { question: "Which port for HTTP?", options: ["80", "443", "21", "25"], answer: 0 },
  { question: "Which traversal of BST gives sorted order?", options: ["Preorder", "Inorder", "Postorder", "Level order"], answer: 1 },
  { question: "Average complexity of Quick sort", options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], answer: 1 },
  { question: "Which is NOT a transport protocol?", options: ["TCP", "UDP", "IP", "SCTP"], answer: 2 },
  { question: "Which keyword in Java for inheritance?", options: ["this", "super", "extends", "implements"], answer: 2 },
  { question: "Which OSI layer is responsible for compression and encryption?", options: ["Application", "Presentation", "Session", "Transport"], answer: 1 },
  { question: "Hash function ideal output", options: ["Fixed size", "Variable size", "Always 0", "Random numbers"], answer: 0 },
  { question: "Which DDL command modifies table structure?", options: ["UPDATE", "ALTER", "INSERT", "DELETE"], answer: 1 },
  { question: "Time complexity of finding min in sorted array", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0 },
  { question: "Which OS uses paging?", options: ["DOS", "MS Windows / Linux", "BIOS", "BIOS only"], answer: 1 },
  { question: "Which feature distinguishes class from struct in C++?", options: ["Default access", "Memory", "Speed", "Size"], answer: 0 },
  { question: "What is critical section?", options: ["Code accessing shared resource", "Slow code", "Loop", "Function"], answer: 0 },
  { question: "Which is reflexive relation property?", options: ["a R a", "a R b → b R a", "a R b ∧ b R c → a R c", "All"], answer: 0 },
  { question: "Network address translation (NAT) operates at", options: ["Physical", "Data Link", "Network", "Transport"], answer: 2 },
  { question: "ER diagram represents", options: ["Entities and relations", "Events and routines", "Errors", "Encapsulation"], answer: 0 },
  { question: "Which is non-clustered index?", options: ["Same as primary key", "Separate structure pointing to data", "Always unique", "Same as foreign"], answer: 1 },
  { question: "Which is NOT a NoSQL type?", options: ["Document", "Key-value", "Graph", "Relational"], answer: 3 },
  { question: "Which algorithm avoids deadlock?", options: ["Round robin", "Banker's", "FCFS", "Shortest job"], answer: 1 },
  { question: "Default value of int in Java is", options: ["null", "0", "1", "Garbage"], answer: 1 },
  { question: "Which is true for stack memory?", options: ["LIFO", "FIFO", "Random", "Sorted"], answer: 0 },
  { question: "Which is connectionless protocol?", options: ["TCP", "UDP", "FTP", "SSH"], answer: 1 },
  { question: "Number of nodes in complete BT of height h", options: ["2^h", "2^(h+1)-1", "h+1", "2h"], answer: 1 },
  { question: "Big-O of bubble sort worst case", options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], answer: 2 },
];

const cseHard = [
  { question: "Time complexity of finding LCA in a balanced BST is", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 1 },
  { question: "Which algorithm finds shortest path with negative weights but no negative cycles?", options: ["Dijkstra", "BFS", "Bellman-Ford", "Floyd-Warshall only"], answer: 2 },
  { question: "Strassen's matrix multiplication has complexity", options: ["O(n^2)", "O(n^3)", "O(n^2.81)", "O(n log n)"], answer: 2 },
  { question: "Which scheduler manages long-term processes?", options: ["short-term", "long-term", "medium-term", "I/O"], answer: 1 },
  { question: "BCNF is stricter than", options: ["1NF only", "2NF only", "3NF only", "all of 1NF, 2NF, 3NF"], answer: 3 },
  { question: "Which is NOT a property of a transaction (ACID)?", options: ["Atomicity", "Consistency", "Isolation", "Distribution"], answer: 3 },
  { question: "Which problem is NP-complete?", options: ["sorting", "binary search", "Travelling Salesman (decision)", "matrix multiplication"], answer: 2 },
  { question: "Pumping Lemma is used to prove a language is NOT", options: ["context-free", "regular", "context-sensitive", "decidable"], answer: 1 },
  { question: "Number of TCP connection states is", options: ["6", "8", "10", "11"], answer: 3 },
  { question: "Inversion count of array using merge sort runs in", options: ["O(n)", "O(n^2)", "O(n log n)", "O(log n)"], answer: 2 },
  { question: "Which CPU scheduling minimizes average waiting time (theoretically)?", options: ["FCFS", "Round Robin", "Shortest Job First", "Priority"], answer: 2 },
  { question: "Which algorithm uses dynamic programming?", options: ["Quick sort", "Merge sort", "Floyd-Warshall", "Heap sort"], answer: 2 },
  { question: "Two-phase locking ensures", options: ["serializability", "deadlock-freedom", "fairness", "starvation-freedom"], answer: 0 },
  { question: "Which language is recognized by a deterministic PDA but not by a finite automaton?", options: ["a^n", "a^n b^n", "(ab)*", "any regular language"], answer: 1 },
  { question: "Which protocol is connectionless?", options: ["TCP", "UDP", "FTP", "SSH"], answer: 1 },
  { question: "Bloom filter trades correctness for", options: ["space and false positives", "time and accuracy", "memory and time", "none"], answer: 0 },
  { question: "Number of distinct BSTs with n=4 keys is (Catalan)", options: ["10", "14", "20", "24"], answer: 1 },
  { question: "Which of the following is true for a Red-Black tree height?", options: ["O(n)", "O(sqrt n)", "O(log n)", "O(log^2 n)"], answer: 2 },
  { question: "Worst-case complexity of Floyd-Warshall is", options: ["O(V^2)", "O(V^3)", "O(VE)", "O(E log V)"], answer: 1 },
  { question: "Which OS technique avoids fragmentation by using fixed-size blocks?", options: ["segmentation", "paging", "swapping", "compaction"], answer: 1 },
  { question: "B+ tree is used in DBMS primarily for", options: ["caching", "indexing", "compression", "logging"], answer: 1 },
  { question: "Which is true about REST?", options: ["stateful by design", "uses SOAP envelope", "uses HTTP verbs", "always uses XML"], answer: 2 },
  { question: "Asymptotic complexity of solving N-Queens by backtracking is", options: ["O(N!)", "O(N^2)", "O(2^N)", "O(N log N)"], answer: 0 },
  { question: "Page table size for 32-bit virtual address with 4 KB pages depends on", options: ["bus width only", "RAM size only", "page-table-entry size", "CPU cores"], answer: 2 },
  { question: "Which protocol uses public-key cryptography for key exchange?", options: ["MD5", "AES", "Diffie-Hellman", "SHA-256"], answer: 2 },
  { question: "Time complexity of Kruskal's algorithm with union-find", options: ["O(V)", "O(E log E)", "O(VE)", "O(V²)"], answer: 1 },
  { question: "Which problem is in P?", options: ["TSP", "SAT", "Sorting", "3-SAT"], answer: 2 },
  { question: "Aho-Corasick algorithm is for", options: ["String matching multiple patterns", "Sorting", "Compression", "Hashing"], answer: 0 },
  { question: "Number of states in DFA accepting strings ending in '01'", options: ["2", "3", "4", "5"], answer: 1 },
  { question: "Which protocol uses a 3-way handshake?", options: ["UDP", "TCP", "FTP", "DNS"], answer: 1 },
  { question: "Tree edit distance complexity", options: ["O(n)", "O(n log n)", "O(n²)", "O(n³)"], answer: 3 },
  { question: "Which scheduling minimizes turnaround for batch?", options: ["FCFS", "SJF", "RR", "Priority"], answer: 1 },
  { question: "DFS time complexity using adjacency list", options: ["O(V)", "O(V+E)", "O(VE)", "O(V²)"], answer: 1 },
  { question: "Which sorting is in-place and stable?", options: ["Quick sort", "Merge sort", "Heap sort", "Insertion sort"], answer: 3 },
  { question: "Master theorem case T(n)=2T(n/2)+n", options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], answer: 1 },
  { question: "Which is true about red-black tree?", options: ["Height O(log n)", "Always balanced perfectly", "Never has black nodes", "Always n²"], answer: 0 },
  { question: "Distributed consensus problem solved by", options: ["Paxos / Raft", "Quick sort", "Kruskal", "DFS"], answer: 0 },
  { question: "B-tree of order m has at most ___ children", options: ["m-1", "m", "m+1", "2m"], answer: 1 },
  { question: "Which paging technique avoids external fragmentation?", options: ["Pure paging", "Segmentation", "Compaction", "Swapping"], answer: 0 },
  { question: "Bellman-Ford complexity", options: ["O(V+E)", "O(V log V)", "O(VE)", "O(V²)"], answer: 2 },
  { question: "DFA can recognize", options: ["Regular languages", "CFL", "CSL", "Recursive languages"], answer: 0 },
  { question: "TLB stands for", options: ["Translation Lookaside Buffer", "Table Lookup Block", "Top Level Branch", "Total Logic Buffer"], answer: 0 },
  { question: "Which is true for NP problems?", options: ["Solvable in polynomial time", "Verifiable in polynomial time", "Unsolvable", "Always linear"], answer: 1 },
  { question: "Cyclic prefix is used in", options: ["OFDM", "TCP", "UDP", "BFS"], answer: 0 },
  { question: "Which serialization preserves order?", options: ["JSON Object", "XML", "JSON Array", "YAML"], answer: 2 },
  { question: "Which is NOT a deadlock condition?", options: ["Mutual exclusion", "Hold and wait", "Preemption", "Circular wait"], answer: 2 },
  { question: "Memoization is used in", options: ["Greedy algorithms", "Dynamic programming", "Backtracking", "Linear search"], answer: 1 },
  { question: "Which problem is undecidable?", options: ["Sorting", "Halting problem", "Searching", "Graph coloring"], answer: 1 },
  { question: "Index-only scan in DBMS implies", options: ["No table access needed", "Cluster scan", "Hash join", "Sort merge"], answer: 0 },
  { question: "Topological sort works on", options: ["DAG", "Cyclic graph", "Tree", "Forest"], answer: 0 },
  { question: "Which scheduler uses ready queue?", options: ["Long term", "Short term", "Medium term", "Disk"], answer: 1 },
  { question: "Erasure coding gives", options: ["Encryption", "Redundancy with less storage", "Sorting", "Hashing"], answer: 1 },
  { question: "ACID 'D' means", options: ["Distributed", "Durable", "Decentralized", "Decoded"], answer: 1 },
  { question: "Time complexity of Dijkstra with min-heap", options: ["O(VE)", "O((V+E) log V)", "O(V³)", "O(V²)"], answer: 1 },
  { question: "RSA is based on", options: ["Discrete log", "Integer factorization difficulty", "Hashing", "Subset sum"], answer: 1 },
  { question: "Two-pass assembler does", options: ["Symbol table in pass 1, code in pass 2", "Code first, table later", "Single pass", "Linking only"], answer: 0 },
  { question: "Which CPU pipeline hazard is data dependence?", options: ["Structural", "Data hazard", "Control hazard", "Branch hazard"], answer: 1 },
  { question: "Strongly Connected Components found by", options: ["Tarjan / Kosaraju", "Dijkstra", "Bellman-Ford", "Kruskal"], answer: 0 },
  { question: "Round-Robin time quantum: too small leads to", options: ["Starvation", "High context switching overhead", "Deadlock", "Race"], answer: 1 },
  { question: "Number of possible BSTs with 5 distinct keys", options: ["32", "42", "50", "120"], answer: 1 },
  { question: "Which is a deadlock recovery method?", options: ["Process termination", "Banker's algorithm", "Resource allocation graph", "FCFS"], answer: 0 },
  { question: "Hashing collision resolution", options: ["Chaining / Open addressing", "Sorting", "Linear search", "Indexing"], answer: 0 },
  { question: "Which is true about NoSQL?", options: ["Always faster than SQL", "Schema flexible", "Always relational", "Cannot scale"], answer: 1 },
  { question: "Loadable kernel module helps in", options: ["Static compilation", "Runtime extension of kernel", "User mode app", "Compiler"], answer: 1 },
  { question: "Reentrant code property", options: ["Cannot be shared", "Can be safely interrupted and resumed", "Always single thread", "Slower"], answer: 1 },
  { question: "B+ tree leaf nodes are", options: ["Linked together", "Disconnected", "Same as root", "Empty"], answer: 0 },
  { question: "Which is best for read-heavy workload?", options: ["BST", "Hash table", "Linked list", "Stack"], answer: 1 },
  { question: "Smallest n in 2^n ≥ 1,000,000", options: ["18", "19", "20", "21"], answer: 2 },
  { question: "Compiler phase that handles syntax", options: ["Lexical", "Parser/Syntax", "Semantic", "Optimization"], answer: 1 },
  { question: "DNS uses which transport?", options: ["TCP only", "UDP primarily", "Both UDP and TCP", "ICMP"], answer: 2 },
  { question: "Which OS structure is monolithic?", options: ["Microkernel", "Linux", "MINIX", "QNX"], answer: 1 },
  { question: "Which is true about CAP theorem?", options: ["Cannot have all 3 simultaneously", "Always achieves all 3", "Only for SQL", "Only for NoSQL"], answer: 0 },
  { question: "Greedy algorithm correctness needs", options: ["Optimal substructure & greedy choice", "Always works", "Recursion", "DP"], answer: 0 },
  { question: "Which CPU architecture uses load-store?", options: ["CISC", "RISC", "VLIW", "DSP"], answer: 1 },
  { question: "Network throughput is measured in", options: ["Hertz", "Bps / bps", "Watts", "Bytes"], answer: 1 },
];

function tag(arr, category, difficulty) {
  return arr.map((q, idx) => ({ ...q, category, difficulty, bankIndex: idx }));
}

const allQuestions = [
  ...tag(aptitudeEasy,    "aptitude", "easy"),
  ...tag(aptitudeModerate,"aptitude", "moderate"),
  ...tag(aptitudeHard,    "aptitude", "hard"),
  ...tag(englishEasy,     "english",  "easy"),
  ...tag(englishModerate, "english",  "moderate"),
  ...tag(englishHard,     "english",  "hard"),
  ...tag(cseEasy,         "cseCore",  "easy"),
  ...tag(cseModerate,     "cseCore",  "moderate"),
  ...tag(cseHard,         "cseCore",  "hard"),
];

module.exports = allQuestions;
